### ISSUE TITLE
feat : Leetcode daily challenge reminder!

### ISSUE THREAD

**Issue by harshita214** [harshita214/Chrome-Extension#100]
For developers and coders who wish to be consistent by solving the daily question of leetcode make an extension that will remind them to solve the question of the day and remind them until it's not solved!

- [ ] Remind each day with the question to be solved
- [ ] Link to the question
- [ ] All codes in one folder
- [ ] A good UI
- [ ] Readme file with video of extension implementation

Happy contributions 🎊

**Comment by whiteHatpro** [comment]
I want to work on this issue under JWoC

**Comment by harshita214** [comment]
Sure @whiteHatpro assigning you
All the best 👍

**Comment by Tiya0310** [comment]
I am a gssoc'22 participant. Can I work on this?

**Comment by harshita214** [comment]
Sure @Tiya0310 , Go ahead 
All the best 👍

**Comment by Tiya0310** [comment]
Thank you :)

**Comment by harshita214** [comment]
Update @Tiya0310 
Kindly make a PR by EOD

**Comment by Tiya0310** [comment]
Ok.

**Comment by harshita214** [comment]
@Tiya0310 kindly make a PR by EOD

**Comment by harshita214** [comment]
@Tiya0310 ??

**Comment by harshita214** [comment]
@Tiya0310 make a PR by EOD

**Comment by Sulagna-Dutta-Roy** [comment]
Can I work on this Issue ? Then assign me on this @whiteHatpro @harshita214

**Comment by navyasharma0203** [comment]
Can I work on this issue....part of GSSOC'22??

**Comment by whiteHatpro** [comment]
@Sulagna-Dutta-Roy sure!!
All the best🚀

**Comment by harshita214** [comment]
@Sulagna-Dutta-Roy Update??

**Comment by Sulagna-Dutta-Roy** [comment]
Actually my college running. So I can't able to make this PR. Kindly unassigned me from this. @harshita214

**Comment by ShubhamRawat28** [comment]
Hey, I want to contribute to this please assign it to me jwoc 2k23
