### ISSUE TITLE
feat : clone of Panic button extension

### ISSUE THREAD

**Issue by harshita214** [harshita214/Chrome-Extension#101]
Hide all your tabs at once with one single button and restore them later.
HMA Panic Button - Hide all your tabs at once with one single button and restore them later.

Build an extension "Panic Button" inspired from [this](https://chrome.google.com/webstore/detail/panic-button/faminaibgiklngmfpfbhmokfmnglamcm) 

Ps: Add your own idea to improvise this and in the process make a good UI

Happy contributions 🎊

**Comment by whiteHatpro** [comment]
i want to work on this issue under JWoC

**Comment by harshita214** [comment]
Completed - #109
