### ISSUE TITLE
feat: COVID-19 live statistics chrome extension

### ISSUE THREAD

**Issue by abhilipsasahoo03** [harshita214/Chrome-Extension#104]
A worldwide COVID-19 real-time statistics that provides map of affected countries, sum of population affected, graphs showing the number of currently infected, recovered and death cases under "Daily cases".

**Comment by harshita214** [comment]
Sure @abhilipsasahoo03

**Comment by harshita214** [comment]
Completed - #99 
Thanks for contributing 💙
