### ISSUE TITLE
feat : Make a Calculator Extension

### ISSUE THREAD

**Issue by harshita214** [harshita214/Chrome-Extension#11]
Make a simple calculator

- [ ] Create a folder and add all code
- [ ] Create a readme file for preview
- [ ] Attach a picture of the extension while creating a PR for preview

![image](https://user-images.githubusercontent.com/79797000/151914722-dec5b8af-41da-4649-bcd4-fd4c8da3299f.png)

Happy Contributing 🎊

**Comment by unnikrishnan2002** [comment]
Can I try that for JWOC?

**Comment by harshita214** [comment]
Yes @unnikrishnan2002, Are you interested in building?

**Comment by unnikrishnan2002** [comment]
Yes I have previously made a calculator app . So I am interested in making an extension version of it 😄

**Comment by harshita214** [comment]
Sure, Assigning it to you. All the best @unnikrishnan2002 👍

**Comment by whiteHatpro** [comment]
assign me this issue under JWoC

**Comment by whiteHatpro** [comment]
I want to work on this issue under JWOC

**Comment by unnikrishnan2002** [comment]
@harshita214 I would like to unassign myself from this issue as I can't populate react apps to extensions. You can assign the next person

**Comment by harshita214** [comment]
Hey @whiteHatpro assigning you the issue. All the best 👍
