### ISSUE TITLE
fix:UI enhancement

### ISSUE THREAD

**Issue by IKRA786** [harshita214/Chrome-Extension#114]
As a GSSOC'22 Contributor, I  would like to work on making the UI of the BMI Calculator more interactive.
Please assign this to me.

**Comment by harshita214** [comment]
Sure @IKRA786 You can go ahead with it
All the best 👍

**Comment by harshita214** [comment]
Kindly create a PR for the same 
While submitting a PR 

- [ ] Create a folder of all codes

- [ ] Add a readme file with a proper description of extension, screenshot, and video of extension implementation

- [ ] In PR add what extension you worked by tagging issue and ss of that extension

In case of enhancement of UI kindly change the already presented pictures/video in the readme file 

All the Best

**Comment by harshita214** [comment]
kindly create a PR

**Comment by harshita214** [comment]
@IKRA786 make a PR by today else it will be un-assigned to you

**Comment by harshita214** [comment]
Completed - #155
