### ISSUE TITLE
Theme based site blocker

### ISSUE THREAD

**Issue by SHRIYA1706** [harshita214/Chrome-Extension#115]
Be it a idea or a chrome extension, creativity is a must! Get unproductive sites blocked in a creative way. I want to take this issue. I am a Gssoc'22 Contributor.

**Comment by harshita214** [comment]
Hey @SHRIYA1706 can you explain more briefly

**Comment by SHRIYA1706** [comment]
Basically it will be a shark tank theme based site ad blocker which will be
a chrome extension. We can block any site of our choice by adding that
Chrome extension in our browser just by adding that url manually.

**Comment by SHRIYA1706** [comment]
Is this issue already assigned to me. Can I start working on the same.@harshitar214@Spring-dot

**Comment by harshita214** [comment]
@SHRIYA1706 there are 2 site blockers already present [Block Site](https://github.com/harshita214/Chrome-Extension/tree/main/block%20site) and [AD Blocker](https://github.com/harshita214/Chrome-Extension/tree/main/AD%20BLOCKER), you can take a look at both of them and think of enhancing feature of any one of them. Ping me on discord if you have any queries! I will be happy to help

**Comment by harshita214** [comment]
@SHRIYA1706 ?

**Comment by SHRIYA1706** [comment]
Yes I have gone through it. Will look into it.

**Comment by harshita214** [comment]
> Yes I have gone through it. Will look into it.

Great, let me know if you would like to work on any one of them and what enhancement will you do

**Comment by SHRIYA1706** [comment]
Sure, I will let you know.

**Comment by whiteHatpro** [comment]
@SHRIYA1706 any update?

**Comment by SHRIYA1706** [comment]
Still working on it.
