### ISSUE TITLE
Want to add Password generator extension

### ISSUE THREAD

**Issue by iamrahulmahato** [harshita214/Chrome-Extension#117]
Want to add a Password generator extension to generate strong passwords while surfing the internet

As a participant of GSsOC '22, I would like to work on it.

**Comment by vaibhavmehro** [comment]
I want to work on it which can easily generate the password and can save it also in the user profile

**Comment by harshita214** [comment]
Hey @iamrahulmahato @shreelakshmijoshi @vaibhavmehro this extension is already present in the repo but you all can look at extension and enhance its features or UI
