### ISSUE TITLE
Want to make breaking bad random quote generator Extension

### ISSUE THREAD

**Issue by iamrahulmahato** [harshita214/Chrome-Extension#119]
I will make a chrome extension that will generate random breaking quotes every time you click it.

**Comment by iamrahulmahato** [comment]
As a participant of GSsOC '22, I would like to work on it.

**Comment by negia7265** [comment]
I would like to work on this issue

**Comment by harshita214** [comment]
Can you explain it in brief with features and working

**Comment by iamrahulmahato** [comment]
It will work like an quote extension but rather than any random quote it will generate famous tv show breaking bad famous quotes

Example:
You need to stop focusing on the darkness behind you. The past is the past. Nothing can change what we’ve done.
WALTER WHITE

Features:
Breaking bad famous random quotes
enhance UI

working
When ever user click on extension it will show him breaking bad quotes

**Comment by harshita214** [comment]
Okay sure you can go ahead 👍

**Comment by harshita214** [comment]
Update?
Kindly make PR by EOD

**Comment by iamrahulmahato** [comment]
@harshita214 sorry for the late PR is made #176.Kindly review and merge it.
Thank You

**Comment by iamrahulmahato** [comment]
Hi @harshita214  kindly review my PR

**Comment by harshita214** [comment]
Completed - #176
