### ISSUE TITLE
feat : Make a holiday extension 

### ISSUE THREAD

**Issue by harshita214** [harshita214/Chrome-Extension#12]
Make an extension that will have all dates and days of holidays, Add a search option for holidays along with the option for national, regional, bank holidays. Make use of creativity and add new features on your own to add their usability! Happy contributing 🎊

**Comment by yeshwanth235** [comment]
I am interested in this extension, can you pls assign it to me.

**Comment by harshita214** [comment]
Sure @yeshwanth235, Go ahead assigning it to you. All the best 👍 
When you create PR make sure to add a screenshot for a preview

**Comment by harshita214** [comment]
@yeshwanth235 any updates

**Comment by Devmindtk** [comment]
I would like to work on this issue. could you please explain me which api and tech stack should used here ?

**Comment by harshita214** [comment]
Sure @Devmindtk , HTML CSS JavaScript Chrome API apart from it you can also use any API for fetching calendar/holidays but its totally up to you. If you have more doubts then just ping me :)

**Comment by Devmindtk** [comment]
please assign this issue to me @harshita214

**Comment by harshita214** [comment]
Sure @Devmindtk , All the best 👍

**Comment by harshita214** [comment]
@Devmindtk update?

**Comment by harshita214** [comment]
@Devmindtk?

**Comment by Devmindtk** [comment]
> @Devmindtk?

done by tomorrow

**Comment by harshita214** [comment]
@Devmindtk ??

**Comment by r3yc0n1c** [comment]
Is this issue up for grab? I would like to work on this issue under JWOC'22

**Comment by harshita214** [comment]
There is no API, you have to implement it actually since I don't think there is an API for the same

**Comment by harshita214** [comment]
@r3yc0n1c assigning you, All the best 👍

**Comment by harshita214** [comment]
@r3yc0n1c update?

**Comment by kalashvasaniya** [comment]
Please assign this issue to me.!

**Comment by kalashvasaniya** [comment]
Thank you for assigned me!

**Comment by harshita214** [comment]
@kalashvasaniya you are part of which program can you mention so that I can provide right tags

**Comment by kalashvasaniya** [comment]
> @kalashvasaniya you are part of which program can you mention so that I can provide right tags

GSSoC - Contributor

**Comment by harshita214** [comment]
Okay sure, Also kindly create a PR for same

**Comment by harshita214** [comment]
@kalashvasaniya Kindly make a holiday extension as calendar one is already present you enhance its features or UI if you want

**Comment by kalashvasaniya** [comment]
The calendar Which is already present Is not attractive & Good UI but My calendar is dynamic & Have Great UI

https://user-images.githubusercontent.com/88212870/156866502-dafd6893-9080-4dcd-9645-3c662365c461.mov

**Comment by kalashvasaniya** [comment]
> @kalashvasaniya Kindly make a holiday extension as calendar one is already present you enhance its features or UI if you want

It took 4 days to Make it Pls. Merge it!

**Comment by harshita214** [comment]
> The calendar Which is already present Is not attractive & Good UI but My calendar is dynamic & Have Great UI
> 
>  Screen.Recording.2022-03-05.at.9.14.12.AM.mov

In that kindly enhance the UI of [calendar](https://github.com/harshita214/Chrome-Extension/tree/main/calender%202022), I will assign you a new issue under that category. But for this issue, I can't accept this as clearly holidays are not shown here

**Comment by kalashvasaniya** [comment]
> > The calendar Which is already present Is not attractive & Good UI but My calendar is dynamic & Have Great UI
> > Screen.Recording.2022-03-05.at.9.14.12.AM.mov
> 
> In that kindly enhance the UI of [calendar](https://github.com/harshita214/Chrome-Extension/tree/main/calender%202022), I will assign you a new issue under that category. But for this issue, I can't accept this as clearly holidays are not shown here

Ok I will try!

**Comment by harshita214** [comment]
> > > The calendar Which is already present Is not attractive & Good UI but My calendar is dynamic & Have Great UI
> > > Screen.Recording.2022-03-05.at.9.14.12.AM.mov
> > 
> > 
> > In that kindly enhance the UI of [calendar](https://github.com/harshita214/Chrome-Extension/tree/main/calender%202022), I will assign you a new issue under that category. But for this issue, I can't accept this as clearly holidays are not shown here
> 
> Ok I will try!

Great, I have created an Issue for the same you can get it assigned to you if you are willing to work on that. Also, are you working on [this](https://github.com/harshita214/Chrome-Extension/issues/12) ?

**Comment by kalashvasaniya** [comment]
> > > > The calendar Which is already present Is not attractive & Good UI but My calendar is dynamic & Have Great UI
> > > > Screen.Recording.2022-03-05.at.9.14.12.AM.mov
> > > 
> > > 
> > > In that kindly enhance the UI of [calendar](https://github.com/harshita214/Chrome-Extension/tree/main/calender%202022), I will assign you a new issue under that category. But for this issue, I can't accept this as clearly holidays are not shown here
> > 
> > 
> > Ok I will try!
> 
> Great, I have created an Issue for the same you can get it assigned to you if you are willing to work on that. Also, are you working on [this](https://github.com/harshita214/Chrome-Extension/issues/12) ?

Yaa assign that to me!

**Comment by harshita214** [comment]
Sure, also what about [this](https://github.com/harshita214/Chrome-Extension/issues/12) one? Are you working on this

**Comment by kalashvasaniya** [comment]
assign to someone else Because it's Take lot of time to creat.
Now, I'm working on issue you created to enhance the UI of Calendar :)

**Comment by harshita214** [comment]
Sure @kalashvasaniya

**Comment by shr-code** [comment]
Please assign this issue to me. Could you please tell which api should be used here?

**Comment by harshita214** [comment]
sure @shr-code

**Comment by harshita214** [comment]
While submitting a PR

- [ ]  Create a folder of all codes
- [ ]  Add a readme file with a proper description of the extension, screenshot, and video of extension implementation
- [ ]  In PR add what extension you worked by tagging issue and ss of that extension

 All the best 👍

**Comment by harshita214** [comment]
@shr-code kindly make PR ASAP by today

**Comment by harshita214** [comment]
> @shr-code kindly make PR ASAP by today

@shr-code ?

**Comment by shr-code** [comment]
Hey Harshita! I'm sorry I didn't get any api for this. I had asked you for raising another issue to which you agreed. I want to work on issue #211

**Comment by shreya024** [comment]
@harshita214 @Spring-dot I would like to work on this issue. Kindly assign

**Comment by whiteHatpro** [comment]
@shreya024 assigning this issue to you
All the best
keep me updated with the extension building!!

**Comment by shreya024** [comment]
> @shreya024 assigning this issue to you All the best keep me updated with the extension building!!

Thank you for merging.Kindly add level2 to my PR

**Comment by whiteHatpro** [comment]
@shreya024 the level is already been decided
