### ISSUE TITLE
Customized bookmark that has links to coding platforms like LeetCode, Codeforces, GFG, Codechef. Like an easy launcher for productivity

### ISSUE THREAD

**Issue by Varshini-k-02** [harshita214/Chrome-Extension#121]

**Comment by Varshini-k-02** [comment]
@harshita214 Can you please assign this to me, so that I can start working.

**Comment by harshita214** [comment]
@Varshini-k-02 Will these open the coding profiles of user or just the global website?

**Comment by Varshini-k-02** [comment]
@harshita214 I think initially if the user is new to leetcode and such platforms, he/she will have to login. From next time, the website will login by default unless the user has logged out of the session previously. Hope you get it!

**Comment by harshita214** [comment]
@Varshini-k-02 so there is already an extension [Coding profile Launcher](https://github.com/harshita214/Chrome-Extension/tree/main/Coding%20Profile%20Launcher) for that

**Comment by Varshini-k-02** [comment]
@harshita214 I'm so sorry!

**Comment by harshita214** [comment]
Its alright @Varshini-k-02 no worries

**Comment by YalfamIamShaon** [comment]
Hello @harshita214 I would like to work on this task. I am a GSSOC 22 participant, and I have already created a chrome extension.
And can you tell me more about this, like what are your thoughts regarding the UI. And here is my Chrome extension link 
https://github.com/YalfamIamShaon/tracksy-chrome-extension (you can store important contacts or pages that you want to visit later, my bookmark section was already full, so I made this chrome extension as a personal project)
