### ISSUE TITLE
Want to enhance UI of RandPass extension

### ISSUE THREAD

**Issue by iamrahulmahato** [harshita214/Chrome-Extension#123]
Want to enhance UI of Password generator extension to generate strong passwords while surfing the internet for getting better experience

As a participant of GSsOC '22, I would like to work on it.

**Comment by harshita214** [comment]
Sure @iamrahulmahato Go ahead , all the best 👍

**Comment by harshita214** [comment]
While submitting a PR kindly change the already presented pictures/video in readme file and In PR also Add ss of changes like Before/ After.

**Comment by iamrahulmahato** [comment]
ok i will do that

**Comment by iamrahulmahato** [comment]
The PR is made #151 . Kindly review and merge it.
Thank You

**Comment by harshita214** [comment]
Completed - #151
