### ISSUE TITLE
All by keyboard

### ISSUE THREAD

**Issue by whiteHatpro** [harshita214/Chrome-Extension#126]
the extension that helps u control your page just using the alphabet keys
A keyboard shortcut tool for keyboard-based page navigation and browser tab operations with an advanced omnibar and global shortcuts

**Comment by whiteHatpro** [comment]
@harshita214 i want to work on this issue under JWoC

**Comment by harshita214** [comment]
Sure @whiteHatpro 
All the best 👍

**Comment by harshita214** [comment]
> Kindly add readme and video so that I can close this issue

Kindly add this

**Comment by whiteHatpro** [comment]
@harshita214 added the files as requested!!

**Comment by harshita214** [comment]
Completed - #169
