### ISSUE TITLE
Better Youtube Music Picker 

### ISSUE THREAD

**Issue by Mrjoy832** [harshita214/Chrome-Extension#127]
Hey, I am **TRIDIB BAG** GSSOC'22 contributor, wanted to add a chrome extension that will help to pick better suggestive music from Youtube.
 I will create an extension so that Youtube suggests better music videos, **Actually the problem I face in youtube when You listen to a song It will keep playing over and over again because Youtube seems not to be capable of coming up with new suggestions** so that's the issue I want to fix with my this extension.
I am really wanted to contribute to this topic. 
@harshita214  can you please assign me to this issue, so that I can start contributing to this?

**Comment by harshita214** [comment]
Sure, so will you be searching on the base of tags, kindly explain this

**Comment by Mrjoy832** [comment]
@harshita214, I will create an extension so that Youtube suggests better music videos, Actually the problem I face in youtube when You listen to a song It will keep playing over and over again because Youtube seems not to be capable of coming up with new suggestions so hat's the issue I want to fix with my this extension..Please assign me so that I can go for further contribution to it.

**Comment by harshita214** [comment]
Sure @Mrjoy832 All the best 👍

**Comment by harshita214** [comment]
While submitting a PR

- [ ]  Create a folder of all codes 
- [ ]  Add a readme file with a proper description of extension, screenshot, and video of extension implementation
- [ ]  In PR add what extension you worked by tagging issue and ss of that extension

Create a PR ,All the best 👍

**Comment by Spring-dot** [comment]
@Mrjoy832 Kindly create PR for this issue.

**Comment by Mrjoy832** [comment]
Hey @Spring-dot  please give me 1 day more...I have Hackwithinfy tomorrow so I am Little busy now ..just after that I will create the PRb... sorry for the late

**Comment by Spring-dot** [comment]
@Mrjoy832 okay

**Comment by Mrjoy832** [comment]
Hey @Spring-dot in readme file how to include image from our local machine?

**Comment by harshita214** [comment]
@Mrjoy832 kindly make PR by today

**Comment by Spring-dot** [comment]
> Hey @Spring-dot in readme file how to include image from our local machine?

refer this: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax
