### ISSUE TITLE
feat : Pinterest Extension

### ISSUE THREAD

**Issue by ranimanya** [harshita214/Chrome-Extension#128]
Here I intend to create a Pinterest extension in Chrome browser. It helps us collect, organize, save and revisit our inspiring ideas whenever we wish to.

Please assign me this issue, I'm a Gssoc'22 participant.

**Comment by ranimanya** [comment]
The Pinterest extension allows us to save anything we search on web such as images or websites. When we move our mouse over an image it shows a red 'save' button on top-left corner on the image. Once we click that button, it gets saved to a previously chosen board or we can create a new board. For saving websites, we can open the website and click the Pinterest icon on top-right of the browser and save the website. This eliminates the need of downloading files in our pc.

**Comment by harshita214** [comment]
Sure @ranimanya Go ahead , All the best 👍

**Comment by harshita214** [comment]
While submitting a PR 

- [ ] Create a folder of all codes

- [ ] Add a readme file with proper description of extension , screenshot and video of extension implementation

- [ ] In PR add what extension you worked by tagging issue and ss of that extension

**Comment by harshita214** [comment]
Completed - #173
