### ISSUE TITLE
Personalisation extention for chrome

### ISSUE THREAD

**Issue by shashank2906** [harshita214/Chrome-Extension#129]
Here i would like to create a personalisation chrome extention where we can make a GUI using html and css and we can store our frequently visited links and we can access them from the extention itself .

We can also structure it to have multiple sections for different links like social media links , important websites to visit etc.

**Comment by YalfamIamShaon** [comment]
Hey @shashank2906 please assign me this task. I am a GSSOC 22 participant, and I have already created a chrome extension. I would love to work on this.
And can tell me more about this, like what are your thoughts regarding the GUI. And here is my Chrome extension link 
https://github.com/YalfamIamShaon/tracksy-chrome-extension (you can store important contacts or pages that you want to visit later, my bookmark section was already full, so I made this chrome extension as a personal project)

**Comment by harshita214** [comment]
Sure @shashank2906, we have an extension like [Tab Tracker](https://github.com/harshita214/Chrome-Extension/tree/main/Tab%20Tracker) Kindly take a look and you add the feature of adding frequently visited links, important links in Tab tracker as an enhancement feature!

**Comment by Spring-dot** [comment]
@shashank2906 Are you going ahead to work on enhancement features as mentioned above?

**Comment by shashank2906** [comment]
Sure , i am interested to work on this project 
I have already forked the repo and have already started reading the code , Do i have to create a new issue regarding this or I would be assigned this task

**Comment by Spring-dot** [comment]
I will assign you this task,  also are you part of GSSoC? @shashank2906

**Comment by shashank2906** [comment]
yes i am a part of Gssoc .
Thank you

**Comment by harshita214** [comment]
Update @shashank2906 ?

**Comment by shashank2906** [comment]
Actually working on it , 
Some things are failing . I need some time to complete the changes .

**Comment by harshita214** [comment]
Okay
Create a PR today then

**Comment by shashank2906** [comment]
#191   pull request added

I have created a PR with all the frontend and design changes . Currently working on the functionality part and it is yet to be added .

**Comment by shashank2906** [comment]
The PR (#244) for this issue is merged
