### ISSUE TITLE
doc : Make a readme file 

### ISSUE THREAD

**Issue by harshita214** [harshita214/Chrome-Extension#13]
Make a new readme file adding all the steps after creating an extension, how to view it on the browser. Show all steps like enabling developer mode then click on load unpacked etc. Also, add screenshots so that it's easily understandable. Happy Contributing 🎊

**Comment by yeshwanth235** [comment]
I am interested, assign it to me pls...

**Comment by harshita214** [comment]
Sure @yeshwanth235 assigning it to you. Before you create a PR make a comment here showing the preview of the readme file. Happy Contributing 🎊

**Comment by harshita214** [comment]
Completed - #16
