### ISSUE TITLE
feat : Tag suggester

### ISSUE THREAD

**Issue by harshita214** [harshita214/Chrome-Extension#130]
Often while posting on Instagram or any social media platform we think hard about what can be suitable tags to be added. Create an extension that can not only scan pictures but also words, and give suggested tags for that. Also, add a copy button option.

**Comment by whiteHatpro** [comment]
I want to work on this issue under JWoC

**Comment by harshita214** [comment]
Sure @whiteHatpro 
All the best 👍

**Comment by harshita214** [comment]
Completed - #157
