### ISSUE TITLE
Random News Extension

### ISSUE THREAD

**Issue by Mrjoy832** [harshita214/Chrome-Extension#131]
Hey, I am **TRIDIB BAG** GSSOC'22 contributor, wanted to add a chrome extension that will help to pick random news all over the world which will definitely nourish our knowledge and also provide relief from our boredom .

@harshita214 can you please assign me to this issue, so that I can start contributing to this?

**Comment by harshita214** [comment]
Sure @Mrjoy832 Go ahead, are you using api for same?

**Comment by Mrjoy832** [comment]
> Sure @Mrjoy832 Go ahead, are you using api for same?

Using api not allowed?

**Comment by harshita214** [comment]
Yes, it's allowed, I am asking if you are building using API or using any other method?

**Comment by Mrjoy832** [comment]
I will try 1st without api ..if not able to do so,then I will use api

**Comment by harshita214** [comment]
Okay then how will you generate random updated news all over the world

**Comment by Mrjoy832** [comment]
Let me try please ...I am not sure ..I am making extension on it..if it's done I will make a PR kindly check it and give further feedback and if all are right merge that

**Comment by harshita214** [comment]
Sure, All the best you can start working 
If you have any doubt you can ask on discord server

**Comment by Mrjoy832** [comment]
> Sure, All the best you can start working 
> If you have any doubt you can ask on discord server

I am not able to join the group regarding this project  on discord though I choose self roles  correctly on discord

**Comment by harshita214** [comment]
> > Sure, All the best you can start working
> > If you have any doubt you can ask on discord server
> 
> I am not able to join the group regarding this project on discord though I choose self roles correctly on discord

Can you text your problem in the general channel about this, I will see afterward

**Comment by harshita214** [comment]
While submitting a PR

- [ ]  Create a folder of all codes 
- [ ]  Add a readme file with a proper description of extension, screenshot, and video of extension implementation
- [ ]  In PR add what extension you worked by tagging issue and ss of that extension

All the best 👍

**Comment by Mrjoy832** [comment]
> > > Sure, All the best you can start working
> > > If you have any doubt you can ask on discord server
> > 
> > I am not able to join the group regarding this project on discord though I choose self roles correctly on discord
> 
> Can you text your problem in the general channel about this, I will see afterward

Sure I will do

**Comment by Mrjoy832** [comment]
@harshita214 hey can you say how to add readme file with PR?

**Comment by harshita214** [comment]
Make a file in your folder with Readme.md name and you have to write about your extension, tech stack used, its description, screenshots/videos of extension for its implementation.

Hope this clears out, Also were you able to join the channel?

**Comment by Mrjoy832** [comment]
Yes I joined ..but while making it I am facing some issue in APi, so I am late ..just give me some more

**Comment by harshita214** [comment]
Sure, So create a PR today then

**Comment by Mrjoy832** [comment]
yes till night it will be done

**Comment by Chaitanya1211** [comment]
is this extension still open??

**Comment by Mrjoy832** [comment]
> is this extension still open??

Yes PR is not checked further 🙃

**Comment by Mrjoy832** [comment]
@harshita214  check it.....
