### ISSUE TITLE
feat: JPG2PNG (JPG to PNG Converter) Chrome Extension

### ISSUE THREAD

**Issue by abhilipsasahoo03** [harshita214/Chrome-Extension#132]
Hi, I'm a GSSOC'22 Contributor and I'd like to add a chrome extension wherein you can upload jpg file and get it converted to png file and download it.

**Comment by harshita214** [comment]
Sure @abhilipsasahoo03 you can go ahead with it, Also add the feature of png to jpj option 
All the best 👍

**Comment by abhilipsasahoo03** [comment]
> Sure @abhilipsasahoo03 you can go ahead with it, Also add the feature of png to jpj option 
> All the best 👍 

Hi @harshita214 I'm working on it right away!

**Comment by harshita214** [comment]
@abhilipsasahoo03 Update?
Kindly create a PR by EOD

**Comment by abhilipsasahoo03** [comment]
> @abhilipsasahoo03 Update?
> Kindly create a PR by EOD

Hi @harshita214 I'll be creating a PR by today. Sorry for the delay.

**Comment by harshita214** [comment]
Okay 👍
