### ISSUE TITLE
Extension to keep track for free udemy courses.

### ISSUE THREAD

**Issue by adityaraj079** [harshita214/Chrome-Extension#133]
Hi, I'm a GSSOC'22 Contributor and I'd like to add a chrome extension wherein you can get daily udemy courses links that have become free for some time

**Comment by harshita214** [comment]
Hey @adityaraj079 sure, Go ahead with it 
All the best 👍

**Comment by harshita214** [comment]
While submitting a PR 

- [ ] Create a folder of all codes

- [ ] Add a readme file with proper description of extension , screenshot and video of extension implementation

- [ ] In PR add what extension you worked by tagging issue and ss of that extension

**Comment by harshita214** [comment]
Update @adityaraj079 
Kindly create a PR by EOD

**Comment by harshita214** [comment]
@adityaraj079

**Comment by ishabhthakur** [comment]
hey @Umesh-01   i want to contribute to your project please assign me this issue!! under GSSOC'22 !!!

**Comment by Umesh-01** [comment]
> hey @Umesh-01 i want to contribute to your project please assign me this issue!! under GSSOC'22 !!!

You can go for it just open a issue, I will assign it to you.

**Comment by harshita214** [comment]
@ishabhthakur Sure 
Go ahead, All the best 👍 

@Umesh-01 are you a contributor or mentor?

**Comment by Umesh-01** [comment]
> @Umesh-01 are you a contributor or mentor?

I am Project Admin of Python Assistant
