### ISSUE TITLE
Enhancing CSS properties in Quote Extension

### ISSUE THREAD

**Issue by nickel-28** [harshita214/Chrome-Extension#136]
Hey @harshita214, I want to modify the CSS properties of the quote extension of your repo. Please assign me this issue.

**Comment by harshita214** [comment]
Sure @nickel-28 
Go ahead 👍

**Comment by harshita214** [comment]
While submitting a PR 

- [ ] Create a folder of all codes

- [ ] Add a readme file with proper description of extension , screenshot and video of extension implementation

- [ ] In PR add what extension you worked by tagging issue and ss of that extension

In case of enhancement of UI kindly change the already presented pictures/video in readme file 

All the Best

**Comment by whiteHatpro** [comment]
@nickel-28 any update?
