### ISSUE TITLE
feat : abusive word hider

### ISSUE THREAD

**Issue by ayush-sleeping** [harshita214/Chrome-Extension#14]
So basically , After enabling this extension , it will hide abusive words from every heading and paragraphs .

**Comment by ayush-sleeping** [comment]
Hey @harshita214 , Kindly assign me this issue under JWOC'22

**Comment by harshita214** [comment]
Go ahead @ayush-sleeping , All the best @ayush-sleeping 👍

**Comment by harshita214** [comment]
Completed - #32
