### ISSUE TITLE
Social Media Blocker Extension

### ISSUE THREAD

**Issue by Atharv-110** [harshita214/Chrome-Extension#140]
### This will be an awesome JavaScript Extension some what similar to Ad Blocker but this Social Media Blocker will block all the social media while someone is focusing on his/her work.

@harshita214, please assign me this extension

#### Consider this under GSSoC'22

**Comment by harshita214** [comment]
@Atharv-110 there are 2 site blockers already present [Block Site](https://github.com/harshita214/Chrome-Extension/tree/main/block%20site) and [AD Blocker](https://github.com/harshita214/Chrome-Extension/tree/main/AD%20BLOCKER), you can take a look at both of them and think of enhancing feature of any one of them. Ping me on discord if you have any queries! I will be happy to help

**Comment by Atharv-110** [comment]
This will not be site blocker, it will be only for social media blocker which doesn't make any coder get distracted by them. @harshita214

**Comment by harshita214** [comment]
@Atharv-110 kindly check [this](https://github.com/harshita214/Chrome-Extension/tree/main/block%20site) and view its readme file this is also blocking sites and focus features also.

I can see you are willing to develop a social media blocker then, [this](https://github.com/harshita214/Chrome-Extension/tree/main/AD%20BLOCKER) this is the task which you can do, that is here as of now only some specific websites which are added to the code base are being blocked, what you can do is implement your social media blocker feature here where user can select social media websites which he/she wants to block. Do let me know your views on this.
