### ISSUE TITLE
Random Fact Generator 

### ISSUE THREAD

**Issue by vaslal-324** [harshita214/Chrome-Extension#141]
Hey @harshita214 , **random fact generator** will be a nice extension for chrome which could be done using html, css and js. Please consider this under **GSSOC'22**

**Comment by harshita214** [comment]
Sure @vaslal-324 you can go ahead with it.
Are you going to implement it using a api?

**Comment by vaslal-324** [comment]
> Sure @vaslal-324 you can go ahead with it. Are you going to implement it using a api?

As of now, it's just an array, I tried connecting the API by converting curl to fetch, but it doesn't seem to work
API link : https://fungenerators.com/api/facts/
This has APIs for random riddles as well.

**Comment by harshita214** [comment]
Okay , go ahead

**Comment by harshita214** [comment]
While submitting a PR

- [ ]  Create a folder of all codes
- [ ]  Add a readme file with proper description of extension , screenshot and video of extension implementation
- [ ]  In PR add what extension you worked by tagging issue and ss of that extension

**Comment by harshita214** [comment]
@vaslal-324 Update?
Kindly create PR by EOD

**Comment by vaslal-324** [comment]
The files are ready, sorry, I wanted to upload 2 days back, wasn't able to
coz of urgent work. I'll do it today.

Regards
Vasudha

**Comment by harshita214** [comment]
Completed - #175
