### ISSUE TITLE
fix : UI enhancement of Calendar Extension

### ISSUE THREAD

**Issue by harshita214** [harshita214/Chrome-Extension#142]
Enhance the UI of [Calendar](https://github.com/harshita214/Chrome-Extension/tree/main/calender%202022) extension, 

While submitting a PR kindly change the already presented pictures/video in readme file and In PR also Add ss of changes like Before/ After.

All the Best 👍

**Comment by kalashvasaniya** [comment]
Hey Assign that to me I want to work on this issue.

**Comment by harshita214** [comment]
Sure @kalashvasaniya
