### ISSUE TITLE
Currency Converter Extension 

### ISSUE THREAD

**Issue by Atharv-110** [harshita214/Chrome-Extension#144]
#### It will be an awesome extension which converts the respective currency let's say USD into desired one that's gonna be INR. It will also have an awesome, with easy and Minimalist User UI.

@harshita214 assign me this issue and consider it in GSSoC'22.

**Comment by harshita214** [comment]
Will it be converting to only USD country currency or all

**Comment by Atharv-110** [comment]
It will be converting all the currency into desired and vice versa

**Comment by harshita214** [comment]
Sure go Ahead, All the best 👍

**Comment by harshita214** [comment]
Update ?

**Comment by Atharv-110** [comment]
Raising PR in 2 days as I am indulged in mid semester examination.
