### ISSUE TITLE
Cryptocurrency price update

### ISSUE THREAD

**Issue by harshit0571** [harshita214/Chrome-Extension#146]
I want to create an extension to display crypto prices

**Comment by harshita214** [comment]
Can you explain it more briefly with its features

**Comment by harshit0571** [comment]
i was thinking of an extension where you can search the name of the coin and get its current price, like the weather extension where you get the weather when you search the city.

**Comment by harshita214** [comment]
I see, what if user has not searched and wish to view the current price or compare them , is there any feature like that also?

**Comment by harshit0571** [comment]
we can display a chart of like top 10 coins when it is opened.

**Comment by harshita214** [comment]
Okay , what about comparison ?

**Comment by harshita214** [comment]
@harshit0571 update ?

**Comment by harshit0571** [comment]
i am having trouble  with crypto api.
working on it

**Comment by harshita214** [comment]
@harshit0571 ?

**Comment by harshita214** [comment]
@harshit0571 kindly make a PR by EOD
