### ISSUE TITLE
Random Activity Generator

### ISSUE THREAD

**Issue by shreya024** [harshita214/Chrome-Extension#147]
Feeling bored ? This Random activity generator will suggest an awesome activity to try something new.
@harshita214 Kindly assign me this issue

**Comment by harshita214** [comment]
I see, can you give some example of activity also will this be generated on the basis of time , like if user has 10 minutes and is alone so he/she can do particular activity ...similarly if there are 3 people with 20 minutes they can do activity?

**Comment by shreya024** [comment]
> I see, can you give some example of activity also will this be generated on the basis of time , like if user has 10 minutes and is alone so he/she can do particular activity ...similarly if there are 3 people with 20 minutes they can do activity?

Sure I will be using this https://www.boredapi.com/documentation api so, I can provide options of a solo/group activity but the time thing I wont be able to do ....however alternatively I could provide options on the type of activity

**Comment by harshita214** [comment]
Okay I see, try to implement time feature also like a timer that you have 10 minutes or 30 minutes for this activity

**Comment by harshita214** [comment]
While submitting a PR

- [ ] Create a folder of all codes
- [ ]  Add a readme file with proper description of extension , screenshot and video of extension implementation
- [ ]  In PR add what extension you worked by tagging issue and ss of that extension

**Comment by harshita214** [comment]
Completed - #163
