### ISSUE TITLE
National Day today!

### ISSUE THREAD

**Issue by shr-code** [harshita214/Chrome-Extension#148]
I want to make an extension which tells you which day is celebrated on the present date. Please assign this issue to me.
I am GSSOC contributor

**Comment by harshita214** [comment]
@shr-code you can work on https://github.com/harshita214/Chrome-Extension/issues/12 this issue is similar to your idea proposed

**Comment by harshita214** [comment]
would you like to go ahead with #12 ?

**Comment by shr-code** [comment]
Hey Harshita! Can I raise another issue?

**Comment by harshita214** [comment]
Sure

**Comment by harshita214** [comment]
@shr-code ??

**Comment by harshita214** [comment]
@shr-code you can make a new issue now , closing this issue
