### ISSUE TITLE
ui enhancement of weather extension

### ISSUE THREAD

**Issue by harshit0571** [harshita214/Chrome-Extension#149]
can i work on improving weather extension ui

**Comment by harshita214** [comment]
Sure @harshit0571 go ahead , All the best 👍

**Comment by harshita214** [comment]
While submitting a PR kindly change the already presented pictures/video in readme file and In PR also Add ss of changes like Before/ After.

Add ss in PR also

**Comment by harshita214** [comment]
Kindly create a PR by EOD

**Comment by harshita214** [comment]
PR - #181 
Kindly add a video implementation by today
