### ISSUE TITLE
Chrome Extension: Chrome Ad Blocker

### ISSUE THREAD

**Issue by saujanyaraj07** [harshita214/Chrome-Extension#15]
I absolutely hate having to watch ads. Its my least favourite thing. That is why I want to create an Ad blocker extension. 
An Ad blocker is a software that blocks network requests to and/or from advertising servers. 
Using this chrome extension, Users get fast, sleek ad-blocking capabilities to enjoy sites like Chrome interruption free. 
No more annoying pop-ups, accidental clicks on malware ads and nothing getting in your way of enjoying the internet.

Features:
- [ ] Block annoying ads and banners. 
- [ ] Block pop ups.

**Comment by saujanyaraj07** [comment]
@harshita214 Please assign me this issue under JWOC 2K22

**Comment by harshita214** [comment]
Go ahead and start contributing @saujanyaraj07, assigned to you! All the best 👍

**Comment by whiteHatpro** [comment]
I want to work on this issue under JWOC

**Comment by harshita214** [comment]
Completed - #27
