### ISSUE TITLE
UI enhancement of simple interest calculator

### ISSUE THREAD

**Issue by AkankshaGawade** [harshita214/Chrome-Extension#150]
As a GSSOC'22 Contributor, I would like to work on making the UI of Simple Interest Calculator more interactive.
Please assign this to me.

**Comment by harshita214** [comment]
Sure go ahead 👍 

While submitting a PR kindly change the already presented pictures/video in readme file and In PR also Add ss of changes like Before/ After.

And in PR also attach SS

All the best

**Comment by harshita214** [comment]
Kindly create a PR by EOD

**Comment by harshita214** [comment]
Completed - #177
