### ISSUE TITLE
Modify Quotes extension

### ISSUE THREAD

**Issue by toxic-coderr** [harshita214/Chrome-Extension#153]
Hey @harshita214!!! I want to modify this extension. Please assign this to me.

**Comment by harshita214** [comment]
Can you explain more briefly , how and what you want to modify

**Comment by harshita214** [comment]
@toxic-coderr ?

**Comment by harshita214** [comment]
@toxic-coderr ??

**Comment by whiteHatpro** [comment]
@toxic-coderr please reply within one day or we'll close this issue
