### ISSUE TITLE
feat : Age Calculator

### ISSUE THREAD

**Issue by ayush-sleeping** [harshita214/Chrome-Extension#154]
In this extension , 

First this extension ask you for your Birth Date and Timing of that days , After that it will calculate and it will show you exact ,
your Years, Months , days and hours , minutes and seconds also ,

**Comment by ayush-sleeping** [comment]
@harshita214 . I want to work on this issue under JWOC'22.

**Comment by harshita214** [comment]
Sure @ayush-sleeping , Can you add this feature in the BMI calculator as BMI analysis is also related to AGE
What do you think about it

**Comment by ayush-sleeping** [comment]
> Sure @ayush-sleeping , Can you add this feature in the BMI calculator as BMI analysis is also related to AGE
> What do you think about it

BMI incorporates weight and height, but it does not take age into account.

**Comment by harshita214** [comment]
But BMI changes with age, anyways in that case you can go ahead with it
All the best 👍

**Comment by harshita214** [comment]
Completed - #168
