### ISSUE TITLE
social media blocker

### ISSUE THREAD

**Issue by Nehalmiglani** [harshita214/Chrome-Extension#158]
I would like to create a social media blocker extension that would block the social media sites which keeps us away from distractions.
do assign me.(GSSOC'22)

**Comment by Spring-dot** [comment]
@Nehalmiglani Please check once [Block site](https://github.com/harshita214/Chrome-Extension/tree/main/block%20site), maybe you can enhance that extension.

**Comment by harshita214** [comment]
Yes, @Nehalmiglani you can look at  [AD BLOCKER](https://github.com/harshita214/Chrome-Extension/tree/main/AD%20BLOCKER) extension also for enhancement

**Comment by harshita214** [comment]
@Nehalmiglani would you like to go ahead or not with the issue?

**Comment by whiteHatpro** [comment]
@Nehalmiglani please update

**Comment by MeetaHaldar** [comment]
@harshita214  can you assign me this issue?

**Comment by whiteHatpro** [comment]
> @harshita214 can you assign me this issue?

You will be working as an enhancement of the issue, right?

**Comment by MeetaHaldar** [comment]
can you explain what you want to say?

i was saying that can i make this chrome extension if you assign me this issue then i can work it.
@whiteHatpro

**Comment by MeetaHaldar** [comment]
@whiteHatpro  okay i will see if i can make any change then i will do that
