### ISSUE TITLE
Format Currency Extension

### ISSUE THREAD

**Issue by priyanshi1282** [harshita214/Chrome-Extension#159]
#### This extension will format the entered number into<i> International Currency Number System</i>.
Say you entered <i>number 123456 </i>, this extension will format it into -
INR - ₹1,23,456.00
USD - $123,456.00
JPY - ￥123,456
<b>This will make the entered Amount more readable.</b>

#### Example Screen-Shot
![INRdemo](https://user-images.githubusercontent.com/88632352/156924126-b43bb515-c641-4840-92b0-ef69075b691a.png)

**Comment by harshita214** [comment]
Your idea is good, but what you can do is collaborate with https://github.com/harshita214/Chrome-Extension/issues/144 this issue and add your idea as its feature, what do you think

**Comment by priyanshi1282** [comment]
Hey @harshita214, I reviewed #144 and it includes many types of currency conversion. And my extension provides 3 types of formatting. Also both projects are different.

**Comment by harshita214** [comment]
Okay @priyanshi1282 you can go ahead with this extension, All the best 👍

**Comment by harshita214** [comment]
While submitting a PR

- [ ]  Create a folder of all codes
- [ ]  Add a readme file with a proper description of the extension, screenshot, and video of extension implementation
- [ ]  In PR add what extension you worked by tagging issue and ss of that extension

**Comment by priyanshi1282** [comment]
ok @harshita214 👍

**Comment by harshita214** [comment]
@priyanshi1282 You have added the extension twice kindly revert and remove one duplicate folder
Secondly the image present in readme is not loading, check that also
Also add a video implementation of extension

**Comment by priyanshi1282** [comment]
okay @harshita214 👍

**Comment by priyanshi1282** [comment]
Hey @harshita214  I will be Creating a new pull request with required changes.

**Comment by harshita214** [comment]
Completed - #206 & #183
