### ISSUE TITLE
Making a link saving chrome extension

### ISSUE THREAD

**Issue by Shubhayu-Bhowmick** [harshita214/Chrome-Extension#161]
As a participant of Gssoc'22 I would like to build a working chrome extension that allows you to save links you want to bookmark. 

![link save](https://user-images.githubusercontent.com/69085132/156992475-89730d6c-ea1e-4cc8-9a6d-0fa612dfae8c.png)
It would kinda look like this.

**Comment by Shubhayu-Bhowmick** [comment]
hey! I would like to work on this issue under Gssoc'22. Plz assign me this project.

**Comment by harshita214** [comment]
Sure @Shubhayu-Bhowmick go ahead, can you list down all the features and working

**Comment by harshita214** [comment]
While submitting a PR

- [ ]  Create a folder of all codes
- [ ]  Add a readme file with a proper description of the extension, screenshot, and video of extension implementation
- [ ]  In PR add what extension you worked by tagging issue and ss of that extension

 All the best 👍

**Comment by dvlsatya** [comment]
@harshita214 can you assign this work to me?

**Comment by Spring-dot** [comment]
@Shubhayu-Bhowmick update? 
if @Shubhayu-Bhowmick is not working on this issue, then we will assign to @dvlsatya you.

**Comment by harshita214** [comment]
@Shubhayu-Bhowmick since you are not active, @dvlsatya assigning to you
All the best  @dvlsatya 👍

**Comment by harshita214** [comment]
@dvlsatya can you list down all the features

**Comment by whiteHatpro** [comment]
@dvlsatya update please

**Comment by harshita214** [comment]
@dvlsatya ??
