### ISSUE TITLE
Adding a website blocker extension UI

### ISSUE THREAD

**Issue by aaryahjolia** [harshita214/Chrome-Extension#166]
I made an extension UI to block the social media websites. However, It is not in working condition because I just made an UI on that, so can I add that to this project?

Image for UI extension :

![GSSoC](https://user-images.githubusercontent.com/82600388/157098757-416e9446-346d-4d27-b819-855901e4e767.png)

**Comment by Spring-dot** [comment]
@aaryahjolia there is already [AD BLOCKER](https://github.com/harshita214/Chrome-Extension/tree/main/AD%20BLOCKER) extension. See if you can work on its enhancement.

**Comment by aaryahjolia** [comment]
Ohk sure @Spring-dot 🙌🏻
