### ISSUE TITLE
Pomodoro Extension

### ISSUE THREAD

**Issue by simplyNour** [harshita214/Chrome-Extension#170]
@harshita214 Hi, I want to make an extension for the Pomodoro productivity technique (level-3 since I am a beginner still)
features

    Add/remove tasks to work on
    Start timer and focus on the task for 25 minutes
    alarm rings when pomodoro is up
    show Take a break alert and enable starting other tasks

**Comment by harshita214** [comment]
While submitting a PR

- [ ]  Create a folder of all codes
- [ ]  Add a readme file with a proper description of the extension, screenshot, and video of extension implementation
- [ ]  In PR add what extension you worked by tagging issue and ss of that extension

**Comment by harshita214** [comment]
@NourYoussry ??

**Comment by NourYoussry** [comment]
Some stuff came up I will start on it tomorrow sorry for the delay

**Comment by harshita214** [comment]
@NourYoussry Kindly make a PR by EOD

**Comment by NourYoussry** [comment]
@harshita214 pardon for that, I will start working on the next issue earlier :/

**Comment by harshita214** [comment]
@NourYoussry So are you not working on this?

**Comment by shreya024** [comment]
@harshita214 I would like to work on this issue if no one else is working on it. Kindly assign

**Comment by harshita214** [comment]
@shreya024 assigning you
All the best 👍

**Comment by whiteHatpro** [comment]
@shreya024 thanks for contributing and the labels are added!!

**Comment by shreya024** [comment]
> @shreya024 thanks for contributing and the labels are added!!

No the labels are not yet added.Kindly add the labels to my PR

**Comment by whiteHatpro** [comment]
> > @shreya024 thanks for contributing and the labels are added!!
> 
> No the labels are not yet added.Kindly add the labels to my PR

the labels are present shreya there might be some glitch from your side

**Comment by shreya024** [comment]
> > > @shreya024 thanks for contributing and the labels are added!!
> > 
> > 
> > No the labels are not yet added.Kindly add the labels to my PR
> 
> the labels are present shreya there might be some glitch from your side

The labels are only added to the issue not to my PR. The labels need to be added to my PR in order to increase my score on the leaderboard.Kindly add the labels to my PR.

**Comment by whiteHatpro** [comment]
@shreya024 done!!
