### ISSUE TITLE
GRE Vocabulary Extension

### ISSUE THREAD

**Issue by RiyaBhandari-2811** [harshita214/Chrome-Extension#172]
Hello @harshita214 👋🏻 , as a GSSOC'22 Contributor  i would like to give my contribution to this repo by adding the `GRE Vocabulary Extension` .

> ### What this Extension Do ??
> These Extension help the GRE aspirants get all vocab   `Word + Definition`   at one place and that too in one click , sounds cool 😎right

> ### Tech Stack  📚
>  HTML 🏷
>  CSS 🎨
>  ReactJS 🎁

> Note  :    If you like my idea , pls assign these issue to me and comment down below so that i can start working on this `COOL Extension` .

**Comment by harshita214** [comment]
@RiyaBhandari-2811, There is an extension [Meaning of Word](https://github.com/harshita214/Chrome-Extension/tree/main/Meaning%20of%20word%20extensions) already present for the same, are you also trying to build like this. If yes then you can enhance it , if not then kindly explain your features in brief

**Comment by RiyaBhandari-2811** [comment]
> @RiyaBhandari-2811, There is an extension [Meaning of Word](https://github.com/harshita214/Chrome-Extension/tree/main/Meaning%20of%20word%20extensions) already present for the same, are you also trying to build like this. If yes then you can enhance it , if not then kindly explain your features in brief

My extension is specific to GRE vocab , also it contains features like : 

1. It gives you the **`Synonyms + Examples + Pronunciation`** features .
2. It has clear search also , so basically my div will not just keep growing if i search for more word at single time .

The main feature is the `Pronunciation` one which will help user to get the pronunciation for search word correctly .

**Comment by RiyaBhandari-2811** [comment]
> @RiyaBhandari-2811, There is an extension [Meaning of Word](https://github.com/harshita214/Chrome-Extension/tree/main/Meaning%20of%20word%20extensions) already present for the same, are you also trying to build like this. If yes then you can enhance it , if not then kindly explain your features in brief

Nooo mine is very different , what mine extension does is when ever you click on extension  it will give you new word with its definition and example .  The one your talking about is the word search one mine is not search it is suggesting new word every time .

**Comment by RiyaBhandari-2811** [comment]
What happen @harshita214 ???

**Comment by harshita214** [comment]
@RiyaBhandari-2811 then yours is similar to [Word of the day](https://github.com/harshita214/Chrome-Extension/tree/main/wordoftheday) But it shows constant word for time being, would you like to enhance this one and transform it by adding the above features you are suggesting and changing word each time a button is clicked

**Comment by harshita214** [comment]
@RiyaBhandari-2811 ?

**Comment by RiyaBhandari-2811** [comment]
> @RiyaBhandari-2811 ?

I was thinking of doing of my own , but it will get repeated . I'm working on new extension idea . 
I'm trying to make it rough if it works I'll raise the new issue (I'm figuring out the code/ tech stack) .

**Comment by whiteHatpro** [comment]
> > @RiyaBhandari-2811 ?
> 
> I was thinking of doing of my own , but it will get repeated . I'm working on new extension idea .(Started my work) . I'm trying to make it rough if it works I'll raise the new issue (I'm figuring out the code/ tech stack) .

update?

**Comment by whiteHatpro** [comment]
> @whiteHatpro I'm not working on these issue anymore other wise issues will get repeated and that's wrong .

okay @RiyaBhandari-2811 closing this issue
