### ISSUE TITLE
User languages extension

### ISSUE THREAD

**Issue by 28saakshii08** [harshita214/Chrome-Extension#174]
A pie chart on user profile pages displaying a breakdown of what languages they have used in their repositories.

**Comment by harshita214** [comment]
Sure @28saakshii08 go Ahead 
All the best 👍

**Comment by harshita214** [comment]
While submitting a PR

- [ ]  Create a folder of all codes
- [ ]  Add a readme file with a proper description of the extension, screenshot, and video of extension implementation
- [ ]  In PR add what extension you worked by tagging issue and ss of that extension

**Comment by harshita214** [comment]
Update ?

**Comment by 28saakshii08** [comment]
Working on it.

**Comment by harshita214** [comment]
Kindly make a PR by EOD

**Comment by dvlsatya** [comment]
@harshita214 can you assign this work to me?

**Comment by harshita214** [comment]
@28saakshii08 kindly make a PR by today 
else it will be assigned to @dvlsatya 

@dvlsatya If @28saakshii08 will not work on this then you can work on it after today

**Comment by navyasharma0203** [comment]
@harshita214 Can I work on this issue??

**Comment by whiteHatpro** [comment]
@navyasharma0203 sure!
all the best

**Comment by harshita214** [comment]
@navyasharma0203 update ?

**Comment by navyasharma0203** [comment]
almost done....
