### ISSUE TITLE
Random User Generator Extension

### ISSUE THREAD

**Issue by iamrahulmahato** [harshita214/Chrome-Extension#178]
Project title
(Random User Generator)

Project Description
(Random User Generator will generate random user with name, email and phone no, for this I will use an API which fetches the data from and it will be added to DOM)

Stack:

Html
CSS
JavaScript
Web API

I am a GSSoC Contributor.Please assign me this project

**Comment by harshita214** [comment]
@iamrahulmahato can you explain more about this and its utility also

**Comment by harshita214** [comment]
@iamrahulmahato ?

**Comment by iamrahulmahato** [comment]
@harshita214  It will be a random user generator when you click on the extension it will fetch data through an API and provide the random name, email, phone, and this country with every click it changes

**Comment by Spring-dot** [comment]
@iamrahulmahato what will be its utility?

**Comment by iamrahulmahato** [comment]
@Spring-dot In most of the places programmers don't want to expose the  real identity because of some **privacy** reason it will work there
Thank you
