### ISSUE TITLE
feat : Night Mode extension

### ISSUE THREAD

**Issue by harshita214** [harshita214/Chrome-Extension#18]
White light often strains our eyes especially for developers, coders so why not make their lives easier by implementing night mode. Make an extension that enables night mode. Also, add an on and off button for night mode.

- [ ] Create a folder with all code
- [ ] Add readme with a preview picture of the extension
- [ ] Attach a picture of the extension while creating a PR

Create a PR 🥳
Happy contributing 🎊

**Comment by RajulPE** [comment]
Hi @harshita214, I am interested in working on this under JWOC.

**Comment by harshita214** [comment]
Sure @RajulPE, Go ahead and start building 🚀 All the best 👍

**Comment by harshita214** [comment]
Completed - #21
