### ISSUE TITLE
UI Enhancement of Water-break extension

### ISSUE THREAD

**Issue by kalashvasaniya** [harshita214/Chrome-Extension#180]
UI Enhancement of Water-break extension.

**Comment by harshita214** [comment]
Sure go ahead @kalashvasaniya 
Assigning you 👍

**Comment by harshita214** [comment]
While submitting a PR

- [ ]  Add a readme file with a proper description of the extension, screenshot, and video of extension implementation
- [ ]  In PR add what extension you worked by tagging issue and ss of that extension
