### ISSUE TITLE
Add Dark Mode Extension

### ISSUE THREAD

**Issue by Sulagna-Dutta-Roy** [harshita214/Chrome-Extension#185]
It will be a extension that the user can change the modes dark to day and day to dark. kindly assign me under gssoc'22

**Comment by harshita214** [comment]
Sure @Sulagna-Dutta-Roy go ahead
All the best 👍

**Comment by harshita214** [comment]
While submitting a PR

- [ ]  Create a folder of all codes
- [ ]  Add a readme file with a proper description of the extension, screenshot, and video of extension implementation
- [ ]  In PR add what extension you worked by tagging issue and ss of that extension
