### ISSUE TITLE
Adding dark theme and making extension for all social sites 

### ISSUE THREAD

**Issue by AnkushVerma000** [harshita214/Chrome-Extension#186]
Adding dark theme and making extension for

**Comment by shashank2906** [comment]
On which extention are you working ??

**Comment by harshita214** [comment]
Cany you explain briefly @AnkushVerma000

**Comment by AnkushVerma000** [comment]
A extension that contains all my social median account like this image( on
thr position of loading my all social media accounts are there))  when i
open pop up screen all social media account show there and i thik that i
have to add some features like automatic reply  and others . But i am
student and i dont not more about extension so i  found so many
difficulties at this moment.

**Comment by whiteHatpro** [comment]
@AnkushVerma000 do you want to work on this isssue?
