### ISSUE TITLE
feat : Prank Your Friend Extension  

### ISSUE THREAD

**Issue by mahimk9** [harshita214/Chrome-Extension#19]
I want to work on this issue under JWOC. 
Description : "Prank Your Friend" is an chrome extension to prank a friend. One can add this extension to friend's PC, and enable it.
Once enabled, the text and images present on the website, would change to something funny/anonymous. For ex. Text might change to lorem ipsum, and image to any random images on internet.

**Comment by harshita214** [comment]
Sure @mahimk9 assigning you the issue. All the best 👍

**Comment by mahimk9** [comment]
Thankyou.

**Comment by harshita214** [comment]
Completed - #34
