### ISSUE TITLE
Adding Quote (Good Thoughts) Generator 

### ISSUE THREAD

**Issue by haritdheer** [harshita214/Chrome-Extension#192]
hey @harshita214 . I want to add Quote Generator to your project under Gssoc'22 , Please assign me this project , its my great pleasure if you provide me opportunity to collaborate on this project.

**Comment by aditi10701** [comment]
I am interested in working with this project also I have worked with this before as a website.
sample -https://ecstatic-lamarr-00c5ab.netlify.app/
Please assign me this , I will give my best if given a chance

**Comment by harshita214** [comment]
Hey @haritdheer , @aditi10701 there is already a extension [Quotes](https://github.com/harshita214/Chrome-Extension/tree/main/Quotes) are you developing a different extension ? If yes then kindly expalin your features which are different from the already present one. If not you can work on enhancing the features
