### ISSUE TITLE
The Github Extension

### ISSUE THREAD

**Issue by shreya024** [harshita214/Chrome-Extension#193]
This Extension will showcase the status of pulls, issues and recent comments when provided with the Github username as input. This will make the life of any github user easier as they can readily check their recent github developments.I will develop this using the Github API.

**Comment by shreya024** [comment]
Kindly assign @harshita214 @Spring-dot

**Comment by harshita214** [comment]
Sure go Ahead @shreya024 
All the best 👍

**Comment by harshita214** [comment]
While submitting a PR

 

- [ ] Create a folder of all codes
- [ ]  Add a readme file with a proper description of the extension, screenshot, and video of extension implementation
- [ ]  In PR add what extension you worked by tagging issue and ss of that extension

**Comment by shreya024** [comment]
> While submitting a PR
> 
> * [ ]  Create a folder of all codes
> * [ ]   Add a readme file with a proper description of the extension, screenshot, and video of extension implementation
> * [ ]   In PR add what extension you worked by tagging issue and ss of that extension

Okay,kindly assign it to me.And I would appreciate if you could make it a level 2 since I need to work on the UI and custom javascript. Thank you

**Comment by harshita214** [comment]
Completed - #201
