### ISSUE TITLE
Dictionary Extension

### ISSUE THREAD

**Issue by HardeepPatel** [harshita214/Chrome-Extension#197]

**Comment by whiteHatpro** [comment]
@HardeepPatel can u please provide the description of what you want to achieve in this?

**Comment by HardeepPatel** [comment]
Whichever word you search it will provide you the meaning of it.

**Comment by whiteHatpro** [comment]
@HardeepPatel already have this extension!!
you can work on the enhancement of the extension by the name "meaning of word"

**Comment by ishabhthakur** [comment]
hey @harshita214    i want to contribute to your project please assign me this issue!! under GSSOC'22 !!!  
I have new solution

**Comment by harshita214** [comment]
@ishabhthakur you can work on enhancing the already present one. Also kindly explain your solution

**Comment by whiteHatpro** [comment]
@ishabhthakur please update

**Comment by whiteHatpro** [comment]
@ishabhthakur closing this issue as there is no response from your side
