### ISSUE TITLE
Say It 🔊

### ISSUE THREAD

**Issue by RiyaBhandari-2811** [harshita214/Chrome-Extension#199]
Hello @harshita214 👋🏻 , as a GSSOC'22 Contributor  i would like to give my contribution to this repo by adding the `Say It 🔊` 

<h1 align="center">Say It 🔊</h1>

 ### What this Extension Do ??
> These Extension help the user to convert the Entered `Text To Speech` which will help to learn how to pronounce that entered text . Sounds cool 😎right

 ### Tech Stack  📚
>  HTML 🏷
>  CSS 🎨
>  JS 🎁

` Note  :    If you like my idea , pls assign these issue to me and comment down below so that i can start working on this COOL Extension . `

**Comment by whiteHatpro** [comment]
@RiyaBhandari-2811 yes you can go for it
but try to add some other functionalities as the feature is already available in google voice!!!

Assigning issue to @RiyaBhandari-2811
All the best!!🚀
happy contributing💛

**Comment by RiyaBhandari-2811** [comment]
> @RiyaBhandari-2811 yes you can go for it but try to add some other functionalities as the feature is already available in google voice!!!
> 
> Assigning issue to @RiyaBhandari-2811 All the best!!🚀 happy contributing💛

I'm going to make use of SpeechSynthesisUtterance and that's different from google voice , so i guess it will work for you  .

**Comment by whiteHatpro** [comment]
> > @RiyaBhandari-2811 yes you can go for it but try to add some other functionalities as the feature is already available in google voice!!!
> > Assigning issue to @RiyaBhandari-2811 All the best!!🚀 happy contributing💛
> 
> I'm going to make use of SpeechSynthesisUtterance and that's different from google voice , so i guess it will work for you .

okay, all the best!!!

**Comment by Spring-dot** [comment]
@RiyaBhandari-2811 please make PR for this issue.

**Comment by RiyaBhandari-2811** [comment]
> @RiyaBhandari-2811 please make PR for this issue.

Done

**Comment by RiyaBhandari-2811** [comment]
@harshita214  @Spring-dot  @whiteHatpro  ???

**Comment by harshita214** [comment]
@RiyaBhandari-2811 Good work!
Kindly add a picture of the extension in readme file
