### ISSUE TITLE
bug: Improve Alarm clock extension by adding suitable HTML, CSS code

### ISSUE THREAD

**Issue by harshita214** [harshita214/Chrome-Extension#2]
### Currently in Alarm clock extension HTML, CSS code is not present add it . Create a UI for it

Steps to do
- [ ] Add HTML, CSS code file in Alarm clock folder
- [ ] Show the preview 

After completing these steps, create a Pull Request 🥳
Happy contributing 🎊

**Comment by siddhantsingh-1** [comment]
Can you brief me up on what type of UI is expected in this Alarm clock extension? From my understanding the background.js file creates a new notification after every 0.1 minute, regardless of any user input.

**Comment by harshita214** [comment]
So it will be actually a timer alarm clock and its UI will contain an input option field(with reset icon) for minutes and two buttons start, stop. Yes, the alarm clock js file is not completed and I will open an issue for solving its bug.

**Comment by siddhantsingh-1** [comment]
Okay I understand, I'm working on it
