### ISSUE TITLE
Extension: Quote

### ISSUE THREAD

**Issue by trunmhrshi** [harshita214/Chrome-Extension#20]
Sometimes everyone is frustrated while doing work. This will create an inspirational Quote.

**Comment by trunmhrshi** [comment]
Hey, @harshita214 I want to work on this issue.

**Comment by harshita214** [comment]
Hey, So will it give a new quote every time?

**Comment by trunmhrshi** [comment]
Yes, every time we click on the extension it will give a new quote.

**Comment by harshita214** [comment]
So for that purpose are u thinking of implementing API or writing manually some quotes or something else, can you explain this. Also, are u adding a button to give new quotes every time its clicked

**Comment by trunmhrshi** [comment]
Yes, I will use API to fetch quotes. I will add a button to get new quotes every time.

**Comment by harshita214** [comment]
Great, okay then you can go ahead and start building 🚀 
All the best @trunmhrshi 👍

**Comment by harshita214** [comment]
Completed - #24
