### ISSUE TITLE
Budget Manager Extension

### ISSUE THREAD

**Issue by aka9ksha** [harshita214/Chrome-Extension#200]
Hello 👋🏻 , as a GSSOC'22 Contributor i would like to give my contribution to this repo by adding Budget Manager Extension

**Comment by whiteHatpro** [comment]
@aka9ksha it would be great if u can explain this issue a little bit more

**Comment by aka9ksha** [comment]
**What this Extension Does?**
This extension accepts the spending of user and displays the spending ,users can also set the limit of the spending and get notified when reached the limit .It also has option to reset the amount as well as the limit.

**Tech Stack**
HTML ,CSS AND JS.

**Comment by whiteHatpro** [comment]
@aka9ksha so will it be fetching the expenses we made online on various platforms?

**Comment by aka9ksha** [comment]
No, the user have write the amount spended on its own.

**Comment by whiteHatpro** [comment]
oh okay!!
yes you can sure work on that

@aka9ksha assigning to you!!
all the best!!🚀💛
