### ISSUE TITLE
Page Loading-Time Tracker Extension

### ISSUE THREAD

**Issue by alisha-kamat** [harshita214/Chrome-Extension#210]
An extension that displays the time taken followed by an indicator (red/yellow/green), depending on how fast/slow the page loads.

**Comment by harshita214** [comment]
Can you explain this issue briefly

**Comment by alisha-kamat** [comment]
It measures the loading time of a page along with an indicator.

For instance, if a page takes an unusually long time to load, the extension will display a red colored warning message indicating it. But if it loads within the given threshold, the indicator will turn green. And so on for yellow.

**Comment by harshita214** [comment]
Okay go ahead you can work on this 
All the best 👍
