### ISSUE TITLE
Paraphrasing Extension

### ISSUE THREAD

**Issue by shr-code** [harshita214/Chrome-Extension#211]
Hey, I'm a GSSOC contributor and would like to work on paraphrasing extension. Please assign this issue to me!

**Comment by shr-code** [comment]
@harshita214 i couldn't find any api for that.. it was not feasible. I want to work on this issue. Could you please assign this to me?

**Comment by shr-code** [comment]
@harshita214 ?

**Comment by harshita214** [comment]
@shr-code sure 
Go ahead, All the best 👍 
Assigning you

**Comment by whiteHatpro** [comment]
@shr-code update?
