### ISSUE TITLE
Want to add a youtube link extension 

### ISSUE THREAD

**Issue by iamrahulmahato** [harshita214/Chrome-Extension#212]
Motive:
Whenever you open youtube you have to go through a lot of steps to find out your recent youtube videos so, I will make an extension that will provide the top 10 recent youtube videos you watched with a link

stack:
Html
CSS
JS

I am a GSSoC Contributor.

**Comment by pranv-sonawane** [comment]
Hey i can help you with that if you want! i am a GSSoC Contributor too

**Comment by harshita214** [comment]
@iamrahulmahato will these recent videos be fetched from history? or suggestions of video

**Comment by iamrahulmahato** [comment]
@iamrahulmahato it will be recent videos

**Comment by iamrahulmahato** [comment]
@harshita214 it will fetch the recent app

**Comment by iamrahulmahato** [comment]
@harshita214  sorry I mean to say it will fetch videos from recent history

**Comment by ishabhthakur** [comment]
hey @harshita214    i want to contribute to your project please assign me this issue!! under GSSOC'22 !!!  
I have new solution regarding 
it

**Comment by harshita214** [comment]
@iamrahulmahato Sure go-ahead, are you using API for the same?

@ishabhthakur sure kindly elaborate your idea we can work on it if its implementable

**Comment by iamrahulmahato** [comment]
@harshita214 yes I will use an API not only that I will add two functions in the extension where you can not only get the recent video also get the link of a recent video so that with one click you can share your video easily

**Comment by harshita214** [comment]
@iamrahulmahato great!
Have you completed?

**Comment by iamrahulmahato** [comment]
@harshita214 no just working on it

**Comment by iamrahulmahato** [comment]
@harshita214 no just working on it

**Comment by iamrahulmahato** [comment]
@harshita214 sorry I  will not be able to submit the issue
I made everything from design to the logic of js but the issue is the API that I got is not fetching your recent videos but what its doing is fetching the recent videos of the person who made that API
