### ISSUE TITLE
Random anime pictures

### ISSUE THREAD

**Issue by Akriti-007** [harshita214/Chrome-Extension#216]
Hello! I am GSSoC 2022 contributor. I want to add an extension which shows random anime pictures.

**Comment by Akriti-007** [comment]
It will show random anime images like that of Naruto and many more, and is a great hangout (especially for anime fans).

**Comment by ishabhthakur** [comment]
hey @harshita214   i want to contribute to your project please assign me this issue!! under GSSOC'22 !!!  
I have new solution regarding this issues please if the assigned person not working on it

**Comment by harshita214** [comment]
@Akriti-007 so apart from randomly showing the picture what else will it show? Like name, description etc? Also any feature

**Comment by Akriti-007** [comment]
Yes name will be shown along with picture!

**Comment by harshita214** [comment]
Okay 
Any other feature?

**Comment by harshita214** [comment]
@Akriti-007 kindly create PR
