### ISSUE TITLE
Bug Issue : Chrome will no longer accept Manifest V2 extension updates in the Chrome web browser.

### ISSUE THREAD

**Issue by iamrahulmahato** [harshita214/Chrome-Extension#218]
We need to change the manifest v2 to v3
project name:- Random Jokes Extension
![bug 1](https://user-images.githubusercontent.com/49890655/161279705-a15b4f70-e36a-480c-afa2-494d308f555e.jpg)
![bug 2](https://user-images.githubusercontent.com/49890655/161279725-93ad3f3d-7329-4a09-b648-59f93dcdddb4.jpg)
I would like to solve the issue

**Comment by iamrahulmahato** [comment]
I'm a GSSOC22 contributor

**Comment by harshita214** [comment]
Sure @iamrahulmahato 
Assigning you

**Comment by iamrahulmahato** [comment]
@harshita214  The PR is made #229  . Kindly review and merge it.
Thank You
