### ISSUE TITLE
doc: Minor Enhancement in README.md

### ISSUE THREAD

**Issue by abhilipsasahoo03** [harshita214/Chrome-Extension#220]
**Description**

I'd like to make minor enhancements in README.md file, such as:
- Updation in the Chrome Extensions List/Table
- Adding Code Of Conduct File and its corresponding section in README
- Minor documentation improvements

I'd like to make this contribution under GSSOC'22

**Comment by abhilipsasahoo03** [comment]
Hi @harshita214 kindly assign me this issue so that I can make a PR

**Comment by harshita214** [comment]
Sure @abhilipsasahoo03 
All the best 👍
