### ISSUE TITLE
New Extension HackTrack

### ISSUE THREAD

**Issue by dee-ksha** [harshita214/Chrome-Extension#221]
I wish to add a new extension through which you can keep track of the upcoming hackathons and contests you register for by adding them to the list. It can also be used as a To-Do List.

**Comment by harshita214** [comment]
@dee-ksha will there be a list of hackathons/events or does the user has to add that manually?

**Comment by harshita214** [comment]
@dee-ksha ??

**Comment by dee-ksha** [comment]
> @dee-ksha ??

I'm still working on it. I'll be creating a pr soon.

**Comment by Spring-dot** [comment]
@dee-ksha update?
