### ISSUE TITLE
New Extension : github unfollwers

### ISSUE THREAD

**Issue by komalswami** [harshita214/Chrome-Extension#223]
Chrome extension for listing people who unfollowed you on Github in the notification.

**Comment by harshita214** [comment]
Can you explain it more
and make it instead for follow, like notification when someone followed

**Comment by komalswami** [comment]
sounds good I can do that as well.

**Comment by harshita214** [comment]
Great go ahead
All the best 👍

**Comment by harshita214** [comment]
@komalswami Create a PR by EOD

**Comment by komalswami** [comment]
hey I am working on it but it will take some time.

**Comment by whiteHatpro** [comment]
@komalswami please update the extension asap
