### ISSUE TITLE
Adding Stop Watch Extension

### ISSUE THREAD

**Issue by TG922** [harshita214/Chrome-Extension#224]
### Description

- Adding Stop Watch Chrom Extension

### Tech Stack
- HTML, CSS and JS.

I'm a GSSOC '22 contributor and would like to work on this issue

**Comment by harshita214** [comment]
@TG922 there is already [Timer](https://github.com/harshita214/Chrome-Extension/tree/main/Timer) extension, is your idea similar to this. If yes, then you can enhance this. If not then kindly explain your idea more briefly with its features

**Comment by TG922** [comment]
Is it done already @harshita214 ?? Ok i am closing this issue
