### ISSUE TITLE
Add CODE_OF_CONDUCT.md file

### ISSUE THREAD

**Issue by Sukriti-m** [harshita214/Chrome-Extension#225]
### Problem
CODE_OF_CONDUCT file is missing in this repository.

### Solution
I want to add the CODE_OF_CONDUCT.md file to this repo.

### Additional context
I am contributor at GSSoC '22. Please assign this issue to me.

**Comment by harshita214** [comment]
@Sukriti-m Sure go ahead
All the best 👍
