### ISSUE TITLE
Add Issue Template and PR template

### ISSUE THREAD

**Issue by abhilipsasahoo03** [harshita214/Chrome-Extension#234]
I think adding issue template and PR template will make content of issues and PR consistent and easy to track. Also, I think contributors will also find issues and PRs easy to write by following the template. I'm a GSSOC'22 contributor and I'd like to be assigned this issue.

**Comment by abhilipsasahoo03** [comment]
@harshita214 please assign me this issue.

**Comment by harshita214** [comment]
Yes this is a good idea @abhilipsasahoo03 

Can you send the draft template before creating PR

**Comment by abhilipsasahoo03** [comment]
> Yes this is a good idea @abhilipsasahoo03 
> 
> Can you send the draft template before creating PR

Hi @harshita214 here are the screenshots of the issue templates and PR template I have planned to add:
![Screenshot_2022-04-09-16-39-46-892_com.android.chrome.jpg](https://user-images.githubusercontent.com/80174214/162569464-8469b9b9-12cb-4fcb-9aea-e98fed8d0773.jpg)![Screenshot_2022-04-09-16-39-54-900_com.android.chrome.jpg](https://user-images.githubusercontent.com/80174214/162569466-4bccb290-b765-44fc-a3f6-ac64303ad582.jpg)![Screenshot_2022-04-09-16-40-00-341_com.android.chrome.jpg](https://user-images.githubusercontent.com/80174214/162569468-299df978-bc6c-4d21-9fbe-8e0b2424dc6a.jpg)![Screenshot_2022-04-09-16-40-09-057_com.android.chrome.jpg](https://user-images.githubusercontent.com/80174214/162569473-4e67af92-0505-4413-81b8-21929384e20a.jpg)![Screenshot_2022-04-09-16-40-16-939_com.android.chrome.jpg](https://user-images.githubusercontent.com/80174214/162569477-330eb4c5-9856-417c-b1a6-b74918ad0c05.jpg)
