### ISSUE TITLE
Currency Converter

### ISSUE THREAD

**Issue by Sukriti-m** [harshita214/Chrome-Extension#239]
An extension that will convert the INR to USD and vice-versa. This will be helpful to the users as sometimes one needs to compare the prices.

I am contributor at GSSoC22. Please assign this issue to me.

@harshita214

**Comment by harshita214** [comment]
@Sukriti-m There is [currency converter](https://github.com/harshita214/Chrome-Extension/tree/main/Currency%20Convertor) already present you can look to enhance this
OR if your idea is different from this then kindly explain briefly

**Comment by whiteHatpro** [comment]
@Sukriti-m closing this issue are there is no response from your side
In future if u have any idea we'll open this for you
