### ISSUE TITLE
Drinking Water Extension

### ISSUE THREAD

**Issue by khushbooshakya** [harshita214/Chrome-Extension#240]
### Is your extension request related to a problem? Please describe.

This small extension will help in reminding of drinking at regular intervals of time.As we all know that we got busier with our laptops than we forget to take care of our health . Staying hydrated is an essential part of maintaining good health. 

### Describe the solution you'd like.

This simple extension will help to remind drink water periodically. 

### Describe alternatives you've considered.

This extension have the option to set a time interval to show the notification.has

### Add any other context or screenshots about the extension here.

https://drive.google.com/file/d/1-8Mh0ygrfjkeQWN0dmoXfnYLc4gYBV0Y/view?usp=sharing

**Comment by harshita214** [comment]
@khushbooshakya there is already an [extension](https://github.com/harshita214/Chrome-Extension/tree/main/Water%20breaksl) present you can enhance its features or if your idea is different from this then explain it briefly

**Comment by Spring-dot** [comment]
@khushbooshakya update? If you are thinking of any enhancement?
