### ISSUE TITLE
MP4 to MP3 Video Converter

### ISSUE THREAD

**Issue by shreya024** [harshita214/Chrome-Extension#241]
### Is your extension request related to a problem? Please describe.

This extension will convert any Youtube,SoundCloud,Twitter,Instagram video(mp4) to mp3 format

### Describe the solution you'd like.

I will use yt-download.org api to make the extension

### Describe alternatives you've considered.

I would like to work on this issue. Kindly assign @harshita214 

### Add any other context or screenshots about the extension here.

Besides having a download button,I am thinking of making a send button as well to send the generated mp3

**Comment by harshita214** [comment]
Sure 
Go ahead @shreya024 
All the best 👍

**Comment by harshita214** [comment]
Completed - #246
