### ISSUE TITLE
Improve styling of chrome extension

### ISSUE THREAD

**Issue by Ashish4321-hub** [harshita214/Chrome-Extension#243]
### What happened?

 Hello,I m gssoc contributor.
Styling of chrome extension is not good .Search bar is not placed well.Text are not not .
Please assign me this issue to improve styling.
![Screenshot_2022-04-12-19-59-58-54_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/88235823/163354603-6a290139-560b-4b98-817a-42287a33cdd8.jpg)

### How can we reproduce this bug?

I can make size of search bar and text are responsive

### Urgency (Optional)

Medium priority

**Comment by harshita214** [comment]
Wrong Repository!
