### ISSUE TITLE
Title: Color Picker Extension

### ISSUE THREAD

**Issue by Sulagna-Dutta-Roy** [harshita214/Chrome-Extension#245]
### Is your extension request related to a problem? Please describe.

I will be creating simple extension that can pick any color of the website. It will help us to find the color codes.

### Describe the solution you'd like.

I will use html5, css, javascript.

### Describe alternatives you've considered.

NA

### Add any other context or screenshots about the extension here.

Please assign me this Issue

**Comment by Sulagna-Dutta-Roy** [comment]
@harshita214 kindly assign me this Issue

**Comment by harshita214** [comment]
@Sulagna-Dutta-Roy 
There is an extension similar to this [Color Picker](https://github.com/harshita214/Chrome-Extension/tree/main/Hex%20code%20color%20picker%20extension) and another one [Dark Theme Color Palette Generator](https://github.com/harshita214/Chrome-Extension/tree/main/Dark%20ColorGen)

You can think of enhancing any one of them 
Or if your idea is different from the above 2 then kindly explain it more briefly

**Comment by Sulagna-Dutta-Roy** [comment]
Oh Similar to this extension. But my extension will work on websites , when user will click the button it will fetch the color of the website and display it.

**Comment by harshita214** [comment]
@Sulagna-Dutta-Roy the color picker also does the same, You can view it.

Also as of fetch will it automatically displays all color of the website? Or through a pointer?

**Comment by Sulagna-Dutta-Roy** [comment]
Yeah I checked. Similar project it is.

**Comment by Sulagna-Dutta-Roy** [comment]
Can I close it ??? I will make new Issue then.

**Comment by harshita214** [comment]
Sure!
