### ISSUE TITLE
Submit response Popup button

### ISSUE THREAD

**Issue by Kumar-Ankit56** [harshita214/Chrome-Extension#247]
Hii I'm a GSSoc22 contributor and I'm looking to make a pr request in this repo regarding my project which is a Submit response Popup button.

The idea behind this project :
This is just like when we submit our response then a popup arises for confirmation.

How does it work
Here we have a submit button that will preview when you will click on submit button then thanks popup confirmation button will be popup out from the top.

for more details please refer to the  attached images.
![Screenshot (118)](https://user-images.githubusercontent.com/73521123/163663099-fdaba87c-6e60-4b5d-9f27-2bca80315b61.png)
![Screenshot (119)](https://user-images.githubusercontent.com/73521123/163663104-28ab7ded-c8d5-405f-acab-e1f46fa2e2ca.png)

**Comment by harshita214** [comment]
@Kumar-Ankit56 
Can you explain more briefly  
 What are the use and features

**Comment by whiteHatpro** [comment]
@Kumar-Ankit56 update?
