### ISSUE TITLE
Dice-Roller-game Extension

### ISSUE THREAD

**Issue by Kumar-Ankit56** [harshita214/Chrome-Extension#248]
Hii I'm a GSSoc22 contributor and I'm looking to make a pr request in this repo regarding my project which is a Dice-roller -game.

### The idea behind this project :
Like in our childhood we have played this game on board as we have 2 dice and we through it simultaneously, mate who will get more numbers on dice will win the game.

### How does it work
At the starting you will observe the game name and a start button, After clicking it you will get two dice on the screen, and dice that will have more numbers on them will win the game, and the message will display as player 1 wins, player 2 wins and match draw.

for more details please refer to this attached images.
![Screenshot (125)](https://user-images.githubusercontent.com/73521123/163663380-02741197-7cfd-41d6-b232-7f6a5274381a.png)
![Screenshot (123)](https://user-images.githubusercontent.com/73521123/163663362-f9145683-bd03-4d4c-9c02-2a1f5d22b814.png)
![Screenshot (124)](https://user-images.githubusercontent.com/73521123/163663369-7ae1b270-0a85-456d-bbff-36ec36694bbd.png)

**Comment by harshita214** [comment]
Sure @Kumar-Ankit56 Go ahead with this extension
You have to make a extension of dice roller game

**Comment by harshita214** [comment]
While submitting a PR

- [ ]  Create a folder of all codes
- [ ]  Add a readme file with a proper description of the extension, screenshot, and video of extension implementation
- [ ]  In PR add what extension you worked by tagging issue and ss of that extension

All the best 👍
