### ISSUE TITLE
Calculate Loan Extension: 

### ISSUE THREAD

**Issue by Mrjoy832** [harshita214/Chrome-Extension#250]
### Is your extension request related to a problem? Please describe.

Loan Calculator is an Extension helps to calculate Loan on any principle amount , it will be displayed at screen.

### Describe the solution you'd like.

I will use HTML,CSS,JS for the structure of the UI and working . Json will be used also .

### Describe alternatives you've considered.

NA

### Add any other context or screenshots about the extension here.

@harshita214 , Please assign

**Comment by harshita214** [comment]
@Mrjoy832 Is it like a simple interest/compound interest calculator?

**Comment by Mrjoy832** [comment]
> @Mrjoy832 Is it like a simple interest/compound interest calculator?

Whatever You want between those ..say I will make

**Comment by Mrjoy832** [comment]
> @Mrjoy832 ??

I will make compound interest..is it okay???

**Comment by Mrjoy832** [comment]
> @Mrjoy832 ??

I wanted to say...that which one is required between Simple/compound ? tell me ...I will work on that

**Comment by Spring-dot** [comment]
> > @Mrjoy832 ??
> 
> I wanted to say...that which one is required between Simple/compound ? tell me ...I will work on that

There is already a simple/compound interest calculator. You can work for calculating different types of loans with different time duration for compound interest.
