### ISSUE TITLE
Simple Paint App Extension

### ISSUE THREAD

**Issue by Sulagna-Dutta-Roy** [harshita214/Chrome-Extension#251]
I will be creating one chrome extension using html5, css, javascript.  That user can use the canvas anytime and can do rough works. Please assign me this Issue.

**Comment by whiteHatpro** [comment]
@Sulagna-Dutta-Roy please explain the issue a bit more

**Comment by Sulagna-Dutta-Roy** [comment]
It will be drawing app with paint instruments. User can fill colors, save the images and canvas will be provided here.

**Comment by Sulagna-Dutta-Roy** [comment]
@whiteHatpro Is this Issue relevant or not ?? Let me know so I can open new Issue. Or assign me this

**Comment by whiteHatpro** [comment]
@Sulagna-Dutta-Roy okay assigning to you
All the best!!
