### ISSUE TITLE
UI enhancement of Tab Tracker Extention

### ISSUE THREAD

**Issue by shashank2906** [harshita214/Chrome-Extension#256]
### Which pre-existing extension will you be working on?

Tab Tracker

### Describe your enhancement/improvement

The UI , Design , colors of the extention needs to be improved , so i'll be working on enhancing the UI of the mentioned extention .

**Comment by navyasharma0203** [comment]
Can you work on this issue??....GSSOC'22

**Comment by shashank2906** [comment]
Yes u can if you want , i am already working on it

**Comment by harshita214** [comment]
@shashank2906 ?

**Comment by shashank2906** [comment]
need a little time ,
probably will be completed tomorrow

**Comment by harshita214** [comment]
@shashank2906 ?

**Comment by shashank2906** [comment]
sorry , not able to complete the task ,
U can close the issue 

Thank you

**Comment by harshita214** [comment]
O
