### ISSUE TITLE
Play Beat

### ISSUE THREAD

**Issue by akanksha0209** [harshita214/Chrome-Extension#257]
### Is your extension request related to a problem? Please describe.

No

### Describe the solution you'd like.

A music player which continues to play music as we browse. Please assign this issue to me.

### Describe alternatives you've considered.

It can play music continuously as one browses.

**Comment by akanksha0209** [comment]
Please assign this to me

**Comment by Spring-dot** [comment]
@akanksha0209 There is already an extension [Music Mode](https://github.com/harshita214/Chrome-Extension/tree/main/Music%20Mode) you can think of any enhancement in this.
