### ISSUE TITLE
Tip Calculator Extension

### ISSUE THREAD

**Issue by Sulagna-Dutta-Roy** [harshita214/Chrome-Extension#261]
### Is your extension request related to a problem? Please describe.

I will be creating one simple chrome extension called tip calculator. User can use this extension in any restaurants,malls, food center etc.

### Describe the solution you'd like.

I will use html5, css, javascript for this.

### Describe alternatives you've considered.

NA

### Add any other context or screenshots about the extension here.

Kindly assign me this Issue.

**Comment by whiteHatpro** [comment]
@Sulagna-Dutta-Roy all the best!!
happy contributing
