### ISSUE TITLE
Quiz Extension

### ISSUE THREAD

**Issue by Sukriti-m** [harshita214/Chrome-Extension#262]
### Is your extension request related to a problem? Please describe.

I will make a Quiz Extension in which the user will see a question and then will have to guess the correct answer.

### Describe the solution you'd like.

I will use HTML,CSS ,JS.

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the extension here.

I am contributor at GSSoC '22. Please assign this issue to me.
@harshita214

**Comment by srishtig2412** [comment]
I would like to work on this 
@harshita214

**Comment by Spring-dot** [comment]
@Sukriti-m will you be working on this? @srishtig2412 Since @Sukriti-m  asked first, let her decide.

**Comment by Sukriti-m** [comment]
> @Sukriti-m will you be working on this? @srishtig2412 Since @Sukriti-m asked first, let her decide.

Yes, I'd like to work on this.

**Comment by harshita214** [comment]
@Sukriti-m Kindly create a PR by EOD
