### ISSUE TITLE
Fake Hacks

### ISSUE THREAD

**Issue by SamarthKadam** [harshita214/Chrome-Extension#263]
Can I add this project which removes all the images and replace it with hacked images like it can be used for fake hacking.It is simply
 built using javascript Can I add this?

**Comment by Spring-dot** [comment]
@SamarthKadam  What will be the utility of this? Can you explain in detail?

**Comment by SamarthKadam** [comment]
It is basically pranking the person using this extension. It replaces all the images where user visits with the provided link of image.
It doesn't have any utility but can be used for fun.

**Comment by harshita214** [comment]
Sure go-ahead 
All the best
