### ISSUE TITLE
Github File Structure - Chrome Extension

### ISSUE THREAD

**Issue by hariketsheth** [harshita214/Chrome-Extension#265]
### Is your extension request related to a problem? Please describe.

- Would like to add a Chrome Extension for Github
- This would show the File structure of the Github repositories
- It is very difficult in Github because every time user have to click and check the folder structure. User can't view the full File Structure all at once.

### Describe the solution you'd like.

I would like to implement a Chrome Extension for the same

### Describe alternatives you've considered.

.

**Comment by hariketsheth** [comment]
Assign this to me @harshita214 @whiteHatpro

**Comment by harshita214** [comment]
@hariketsheth can you explain this extension more briefly
