### ISSUE TITLE
Chrome Extension - Dictionary

### ISSUE THREAD

**Issue by hariketsheth** [harshita214/Chrome-Extension#267]
### Is your extension request related to a problem? Please describe.

- Chrome Extension required for word search and meaning 
- A Dictionary would be implemented in Chrome Extension

### Describe the solution you'd like.

- Chrome Extension would be the solution

### Describe alternatives you've considered.

.

**Comment by harshita214** [comment]
@hariketsheth there is already an extension [this](https://github.com/harshita214/Chrome-Extension/tree/main/Meaning%20of%20word%20extensions) which is similar to your idea. You can look at it and enhance it.

With reference to your PR #268 yours is similar to the already present one.
