### ISSUE TITLE
Add Pokemon generator extension

### ISSUE THREAD

**Issue by Priyanshi662** [harshita214/Chrome-Extension#273]
Extension displays random pokemon and shows its type, attack, defense and speed. Below is the screenshot of the extension I made
<img width="261" alt="Screenshot 2022-05-24 000840" src="https://user-images.githubusercontent.com/77521822/169885145-14cf5973-5d33-4931-af56-c81ed5613be9.png">

**Comment by Priyanshi662** [comment]
Kindly assign me this issue under GSSOC'22.

**Comment by harshita214** [comment]
Sure go ahead @Priyanshi662 
All the best
