### ISSUE TITLE
feat : Build a TIC TAC TOE game extension

### ISSUE THREAD

**Issue by harshita214** [harshita214/Chrome-Extension#28]
One of the most popular games we all have played, build its extension and then play it using extension

- [ ] Add all codes in one folder
- [ ] Add preview picture of working extension

Submit a PR 🚀 
Happy contributions 🎊

**Comment by saujanyaraj07** [comment]
@harshita214 Kindly assign me this issue under JWOC'22.

**Comment by whiteHatpro** [comment]
I would like to work on this issue under JWOC

**Comment by harshita214** [comment]
Okay, @saujanyaraj07 👍 assigning you the issue
All the best!

@whiteHatpro kindly look for another issue

**Comment by saujanyaraj07** [comment]
@harshita214 Thankyou!

**Comment by harshita214** [comment]
@saujanyaraj07 update

**Comment by saujanyaraj07** [comment]
@harshita214 will create a pr tomorrow👍 Am almost done

**Comment by harshita214** [comment]
Completed - #47
