### ISSUE TITLE
Stop Watch Extension 

### ISSUE THREAD

**Issue by Mrjoy832** [harshita214/Chrome-Extension#280]
### Is your extension request related to a problem? Please describe.

I want to add  **Stop Watch Extension** , which will be help to countdown time which will be set as input by the users.

### Describe the solution you'd like.

I will use HTML,CSS,JS to implement this.

**Comment by Mrjoy832** [comment]
@harshita214 please assign

**Comment by Jehan-h20220012** [comment]
I would like to help you! Please allow to to contribute to your work as a part of my acedamics which will help you solve your provided issue.

**Comment by Gaurav762** [comment]
Hey @Mrjoy832 
I would like to work on this issue please assign this to me.
Github profile-https://github.com/Gaurav762
Email Id- bhoirgava19it@student.mes.ac.in
Project Approach- I will use HTML, CSS and JavaScript for this issue.
Thanks

**Comment by Mrjoy832** [comment]
> Hey @Mrjoy832 
> I would like to work on this issue please assign this to me.
> Github profile-https://github.com/Gaurav762
> Email Id- bhoirgava19it@student.mes.ac.in
> Project Approach- I will use HTML, CSS and JavaScript for this issue.
> Thanks

Hey I am not owner of this repo, I have not access on this ...so ask to the repo owner

**Comment by Gaurav762** [comment]
Hey @harshita214 
I would like to work on this issue please assign this to me.
Github profile-https://github.com/Gaurav762
Email Id- [bhoirgava19it@student.mes.ac.in](mailto:bhoirgava19it@student.mes.ac.in)
Project Approach- I will use HTML, CSS and JavaScript for this issue.
Thanks
