### ISSUE TITLE
feat : Random Jokes Extension

### ISSUE THREAD

**Issue by harshita214** [harshita214/Chrome-Extension#29]
Create an extension for generating random jokes and making users laugh.

- [ ] Generates random joke every time
- [ ] Add all code in a folder
- [ ] Create a readme file for preview of extension

Happy contributing 🎊

**Comment by harshita214** [comment]
Hey @Aman-Mandal sure, to get started look at the pinned messages on discord I have provided some resources to get started. You can check them out. If you have any further doubt just ping me on discord

**Comment by mrunal736** [comment]
I would like to work on this issue under JWOC

**Comment by whiteHatpro** [comment]
I would like to work on this issue under JWOC

**Comment by harshita214** [comment]
Sure @mrunal736 assigning you the issue! 
All the best 👍 

@whiteHatpro kindly look for another issue

**Comment by mrunal736** [comment]
I've completed the code , is it okay if I make pull request tomorrow?

**Comment by harshita214** [comment]
@mrunal736 update

**Comment by harshita214** [comment]
@mrunal736 I have reviewed your PR, complete it by adding Button feature so that I can merge it

**Comment by mrunal736** [comment]
> @mrunal736 I have reviewed your PR, complete it by adding Button feature so that I can merge it
I'll try to add button feature, is it okay if I make it till tomorrow night.

**Comment by harshita214** [comment]
Okay @mrunal736 , but do it positively

**Comment by harshita214** [comment]
Completed - #33
