### ISSUE TITLE
Decimal, Binary, Hexadecimal & Octal Converter

### ISSUE THREAD

**Issue by ChiaSuen** [harshita214/Chrome-Extension#297]
### Is your extension request related to a problem? Please describe.

I want to add Decimal, Binary, Hexadecimal & Octal Converter extension which can be used to convert number for any of these formats to the other three

### Describe the solution you'd like.

I will use HTML,CSS,JS to implement this.

### Describe alternatives you've considered.

NA

**Comment by NageshMandal** [comment]
I want to work on this issue. Could you please assign it to me.
