### ISSUE TITLE
feat : Add a Hello world Extension

### ISSUE THREAD

**Issue by harshita214** [harshita214/Chrome-Extension#3]
- [ ] Create a folder with all code 
- [ ] Add readme with a preview picture of the extension
- [ ] Attach a picture of extension while creating a PR 

Create a PR 🥳 
Happy contributing 🎊

**Comment by Devmindtk** [comment]
> * [ ]  Create a folder with all code
> * [ ]  Add readme with a preview picture of the extension
> * [ ]  Attach a picture of extension while creating a PR
> 
> Create a PR 🥳 Happy contributing 🎊

I would like to work on this issue @harshita214 please assign it to me.

**Comment by Sneha0324** [comment]
> 
> 
> - [ ] Create a folder with all code 
> - [ ] Add readme with a preview picture of the extension
> - [ ] Attach a picture of extension while creating a PR 
> 
> Create a PR 🥳 
> Happy contributing 🎊 

I would like to work for it.

**Comment by ritika-saha** [comment]
I want to work on this issue under JWOC. Please assign this to me 😊

**Comment by rohit-raj25** [comment]
I want to work on this issue under JWOC

**Comment by stubborn-1508** [comment]
i want to work on this issue.pls assign it to me.

**Comment by raxvab** [comment]
I want to work on this issue under JWOC

**Comment by harshita214** [comment]
Hey @rohit-raj25 , go ahead you can work on this issue. All the best 👍 

@ritika-saha , I already assigned you #4 
@raxvab @stubborn-1508 @Sneha0324 @Devmindtk please look for another issue
