### ISSUE TITLE
feat : Screenshot and Screen Recording Extension

### ISSUE THREAD

**Issue by harshita214** [harshita214/Chrome-Extension#30]
While we are working there are times when we urgently need to take a screenshot or record our screen, so for that times build a extension which will enable user to take screen shot and do screen recording as well! Add feature of resizing the screenshot 

- [ ] Screen Shot feature
- [ ] Screen Recording feature
- [ ] Resizing of Screen Shot
- [ ] All code in one file
- [ ] While creating PR add preview picture and working of extension( ps: Take use of screen recorder to record its working )

All the best 👍 
Happy contributing 🎊

**Comment by KMJ-007** [comment]
I would like to work on this issue under jwoc, can you assign it to me :)

**Comment by harshita214** [comment]
Great @KMJ-007 assigning to you!
All the best 👍

**Comment by harshita214** [comment]
@KMJ-007 update? Kindly create a PR for same

**Comment by KMJ-007** [comment]
I am still working on it, if you want to assign it to other, no problem but it is my first time building chrome extension so it is taking more time :)

**Comment by harshita214** [comment]
No, if you are working then go ahead you are being assigned this issue. It's alright you still have tomorrow try to complete it by tomorrow

**Comment by harshita214** [comment]
@KMJ-007 ?

**Comment by whiteHatpro** [comment]
I want to work on this issue under JWoC

**Comment by harshita214** [comment]
Sure @whiteHatpro, Assigned 👍 
All the best

**Comment by harshita214** [comment]
Completed - #70
