### ISSUE TITLE
Title: Zoom Meet Schedular

### ISSUE THREAD

**Issue by whiteHatpro** [harshita214/Chrome-Extension#307]
### Is your extension request related to a problem? Please describe.

Schedule Zoom meetings directly from Google Calendar

### Describe the solution you'd like.

Zoom Chrome Extension allows you to:
•  Start an instant meeting
•  Schedule a meeting
•  Schedule a meeting for other

### Describe alternatives you've considered.

No alternatives as of now

**Comment by ShubhamRawat28** [comment]
Hey, mentor I want to work on this

**Comment by whiteHatpro** [comment]
please comment in the right format @ShubhamRawat28

**Comment by ShubhamRawat28** [comment]
sorry sir i don't know about the format
can you explain

**Comment by ShubhamRawat28** [comment]
also sir can you suggest me what can i use for this or it will just provide a basic meeting link

**Comment by whiteHatpro** [comment]
@ShubhamRawat28 I have mentioned the details regarding the assignment of the issue. Please look into it

**Comment by whiteHatpro** [comment]
> also sir can you suggest me what can i use for this or it will just provide a basic meeting link

Yes sure we can discuss that, It would be great if we can discuss stuffs over discord section provided to us so kindly ping me there

**Comment by ShubhamRawat28** [comment]
I want to work on this issue under JWOC 
please assign me this issue

**Comment by whiteHatpro** [comment]
@ShubhamRawat28 Assigning to you!!
All the best🚀🌻

**Comment by ShubhamRawat28** [comment]
thanks sir

**Comment by whiteHatpro** [comment]
@ShubhamRawat28 update?

**Comment by ShubhamRawat28** [comment]
sir i have made a manifest.json file and was thinking about the layout of the extension

**Comment by ShubhamRawat28** [comment]
and trying to implement the google calendar api on it

**Comment by ShubhamRawat28** [comment]
hey mentor can i just submit this normal extension for now this works fine but it is not using apis

**Comment by ShubhamRawat28** [comment]
api*

**Comment by whiteHatpro** [comment]
@ShubhamRawat28 yes but please show me the extension before uploading

**Comment by ShubhamRawat28** [comment]
sure

**Comment by whiteHatpro** [comment]
@ShubhamRawat28 please share the ss so that we can proceed further

**Comment by ShubhamRawat28** [comment]
![image](https://user-images.githubusercontent.com/91306245/221232219-42424697-b05c-41e8-9352-0e3d22031006.png)

**Comment by whiteHatpro** [comment]
@ShubhamRawat28 create a pr with all the necessary screenshots and video demo added

**Comment by ShubhamRawat28** [comment]
hey mentor i can't work on this please unassign me this

**Comment by ShubhamRawat28** [comment]
sorry but unable to work on the calendar api
