### ISSUE TITLE
Title: Dictionary

### ISSUE THREAD

**Issue by whiteHatpro** [harshita214/Chrome-Extension#310]
### Is your extension request related to a problem? Please describe.

View definitions easily as you browse the web.

### Describe the solution you'd like.

With this extension, you can:
1) Double-click any word to view its definition in a small pop-up bubble.
2) View the complete definition of any word or phrase using the toolbar dictionary.
3) Store a history of words you've looked up, so you can practice them later.

### Describe alternatives you've considered.

No alternatives as of now

**Comment by ayushanand308** [comment]
@whiteHatpro Can you assign me this issue under JWOC? Also can you change the difficulty because this can take more than a day.

**Comment by whiteHatpro** [comment]
@ayushanand308 assigning to you!!🚀
we can discuss over difficulty later

**Comment by ayushanand308** [comment]
@whiteHatpro  I am getting this error 
Failed to load extension
File
~\Desktop\dict_ex
Error
Invalid value for 'icons'.
Could not load manifest.

when load unpack my directory

**Comment by ayushanand308** [comment]
`{
    "manifest_version": 3,
    "name": "Dictionary ",
    "version": "1.0",
    "description": "Chrome extension that provides the definition of any word on a webpage.",
    "icons": [
        {
            "src": "images/facebook.png",
            "sizes": "16x16",
            "type": "image/png"
        },
        {
            "src": "images/instagram-logo.png",
            "sizes": "48x48",
            "type": "image/png"
        },
        {
            "src": "images/twitter.png",
            "sizes": "128x128",
            "type": "image/png"
        }
    ],
    "permissions": [
        "activeTab",
        "storage",
        "contextMenus"
    ],
    "content_scripts": [
        {
            "matches": [
                "<all_urls>"
            ],
            "js": [
                "contentScript.js"
            ]
        }
    ],
    "action": {
        "default_icon": "images/instagram-logo.png",
        "default_title": "Dictionary",
        "default_popup": "popup.html"
    },
    "background": {
        "service_worker": "background.js"
    }
}
`

this is my json file. PNG file names are just for testing purpose.

**Comment by ayushanand308** [comment]
I am having some problem in all of my chrome extensions. You can assign this to some else.

**Comment by whiteHatpro** [comment]
@ayushanand308 seems like the broken links are corrupting the software needs also the image tags seems to be set, there might be some disrupts
I'll look into it

**Comment by TuhinBanerjee31** [comment]
Can I get assigned to this issue under JWOC ?

**Comment by LuckySingh9897** [comment]
I want to work on this issue under JWOC.

**Comment by whiteHatpro** [comment]
@LuckySingh9897  assigning to you!!🚀
we can discuss over difficulty later

**Comment by TuhinBanerjee31** [comment]
Hey @whiteHatpro , I have put my comment before to work over this issue under JWOC . So why didn't I got assigned ?
