### ISSUE TITLE
Title: Anime Director 

### ISSUE THREAD

**Issue by whiteHatpro** [harshita214/Chrome-Extension#313]
### Is your extension request related to a problem? Please describe.

Ever thought of finding anime difficult on the web?

### Describe the solution you'd like.

Build a chrome extension in which you can easily direct yourselves to your favorite anime with one tap!!

### Describe alternatives you've considered.

NO ALTERNATIVES AS OF NOW

**Comment by LuckySingh9897** [comment]
I want to work on this issue under JWOC.

**Comment by whiteHatpro** [comment]
@LuckySingh9897 Assigning to you!!🚀
