### ISSUE TITLE
Title: Breaking bad chrome extension enhancement

### ISSUE THREAD

**Issue by whiteHatpro** [harshita214/Chrome-Extension#316]
### Which pre-existing extension will you be working on?

Breaking bad chrome extension

### Describe your enhancement/improvement

Need the list of full cast and crew of breaking bad to be shown

**Comment by LuckySingh9897** [comment]
I want to work on this issue under JWOC.

**Comment by LuckySingh9897** [comment]
I want to work on this issue under jwoc.

**Comment by ShubhamRawat28** [comment]
hey mentor i want to work on this please assign this issue to me i think i will be able to complete this one

**Comment by ShubhamRawat28** [comment]
I wanted to work on this under jwoc

**Comment by ShubhamRawat28** [comment]
Hey in this i just have to give documentation or implement code also
