### ISSUE TITLE
Title: Dark Mode chrome extension Enhancement

### ISSUE THREAD

**Issue by whiteHatpro** [harshita214/Chrome-Extension#317]
### Which pre-existing extension will you be working on?

This is a chrome extension that can change your website from dark mood to light mode and vice versa!

### Describe your enhancement/improvement

Need a new button UI for the existing chrome extension: A whole new look

**Comment by vk20july** [comment]
I want to work on this issue under JWOC

**Comment by ayushi1709-20** [comment]
I want to work on this issue under JWOC.
