### ISSUE TITLE
Title: Redesign the whole file Convertor Extension

### ISSUE THREAD

**Issue by whiteHatpro** [harshita214/Chrome-Extension#318]
### Which pre-existing extension will you be working on?

File Converter Chrome extension that can help you convert JPG to PNG and vice versa.

### Describe your enhancement/improvement

The UI seems to be very untypical and the text/functions are not readable: need to change the whole CSS of the extension

**Comment by LuckySingh9897** [comment]
I want to work on this issue under JWOC.
