### ISSUE TITLE
Title: Synonyms Extension  

### ISSUE THREAD

**Issue by LuckySingh9897** [harshita214/Chrome-Extension#329]
### Is your extension request related to a problem? Please describe.

I always need synonyms of a word for that I have to google it so this extension will help in doing so.

### Describe the solution you'd like.

This extension will find the synonyms of word that you have typed.

### Describe alternatives you've considered.

NO

### Add any other context or screenshots about the extension here.

NO

**Comment by whiteHatpro** [comment]
Yes, you can work on it

**Comment by LuckySingh9897** [comment]
Sir my website is working perfectly fine but while making an extension I am getting some problems in manifest.json file.

**Comment by LuckySingh9897** [comment]
I have submitted my pr sir.
