### ISSUE TITLE
[DOCS] <About Contribution Guidelines>

### ISSUE THREAD

**Issue by Sinchan26** [harshita214/Chrome-Extension#332]
### Description

The Guidelines for contributing in the project are not clear,for example in the guideline there is written to take git pull but from where &  how to set?
well for a beginner it should be problematic

### Screenshots

![Screenshot (119)](https://user-images.githubusercontent.com/98639351/223125411-0c611197-178e-4300-84ee-075c7f39821e.png)

**Comment by whiteHatpro** [comment]
@Sinchan26 all the best with the issue
