### ISSUE TITLE
Title: HelperBird chrome extension enhancement [UI] 

### ISSUE THREAD

**Issue by whiteHatpro** [harshita214/Chrome-Extension#341]
### Which pre-existing extension will you be working on?

A Full set of tools for Chrome Extension to be implemented. This includes a lot of features such as Dyslexia Mode, Full Immersive Reader, Text to Speech, Voice Typing, Word Prediction, Screenshot, Color Blindness, Reading List, Bookmarks 

### Describe your enhancement/improvement

Need a new UI with more clear icon design and better UI interaction

**Comment by tusharsh21** [comment]
I want to work under this issue under JWOC
