### ISSUE TITLE
Readme Update :

### ISSUE THREAD

**Issue by ayush-sleeping** [harshita214/Chrome-Extension#36]
Add labels ,
Add Table of content ,
Add Open Source programs this repo has been part of ,
Add Project Mentor ,
Add ( back to top ) and ( bottom ) links ,
Make a table for Extension which are available in this repo. ,
Also - All things categorize it, In a systematic way ......

<br>

I want to work on this issue , under JWOC'22

**Comment by ayush-sleeping** [comment]
hey @harshita214 , I want to work on this issue under JWOC'22 .
and want to make the readme of this amazing repo. more powerful.

**Comment by harshita214** [comment]
Sure go ahead @ayush-sleeping 
You will be responsible for maintaining till the JWOC contribution period ends.
Also ,the Jwoc scoreboard table is already created but it needs to be updated regularly, you can contact me in case of any doubt

**Comment by ishika1501** [comment]
sir i would like to take this .

**Comment by ayush-sleeping** [comment]
I am already working on this issue @ishika1501 ,  take a look on other issues .

**Comment by ishika1501** [comment]
@ayush-sleeping  sure no issue

**Comment by kalashvasaniya** [comment]
Hey,I want to work on this issue can you please aassign me?
