### ISSUE TITLE
feat : word of the day extension

### ISSUE THREAD

**Issue by mnnkhndlwl** [harshita214/Chrome-Extension#37]
I want to work on this issue under JWOC.
Description : whenever user clicks on this extension user will see a random word and its meaning

**Comment by mnnkhndlwl** [comment]
I want to work on this issue under JWOC.
Description : whenever user clicks on this extension user will see a random word and its meaning

**Comment by harshita214** [comment]
Sure @mnnkhndlwl it's a nice idea you can go-ahead
Assigning you, All the best 👍

**Comment by harshita214** [comment]
Completed - #40
