### ISSUE TITLE
Title: Do Your Work Extension

### ISSUE THREAD

**Issue by vedprakashnautiyal** [harshita214/Chrome-Extension#375]
### Is your extension request related to a problem? Please describe.

We often get distracted while working and open social media or other dopamine inducing sites, so to prevent such mishaps this extension is useful.

### Describe the solution you'd like.

This extension shows you a motivational message whenever you open a distracting site while you work, so that you get reminded to get back to your work. I would like to work on this issue under JWOC. Please assign it to me at the earliest.

### Describe alternatives you've considered.

I tried incorporating POMODORO technique but it is not as strict as this one is.

### Add any other context or screenshots about the extension here.

https://user-images.githubusercontent.com/71223796/224526500-febab485-e6e7-4795-a73b-c5150d093bac.mov

**Comment by whiteHatpro** [comment]
@vedprakashnautiyal If you have created the issue you need to comment on it first, get it assigned and then create the pull request for that 

I am making this pr as an exception for now but keep that in mind for later contribution

**Comment by vedprakashnautiyal** [comment]
Okay Sure ,,,,
Thanks ✨
