### ISSUE TITLE
feat : Water break extension

### ISSUE THREAD

**Issue by harshita214** [harshita214/Chrome-Extension#4]
Make an extension that will remind you to take a break from work and have some water. Add features a timer also.

- [ ] Add all codes in a folder
- [ ] Add a readme file with a preview
- [ ] Attach a picture of extension while creating a PR 

Create a PR 🥳
Happy contributing 🎊

**Comment by Sneha0324** [comment]
> Make an extension that will remind you to take a break from work and have some water. Add features a timer also.
> 
> - [ ] Add all codes in a folder
> - [ ] Add a readme file with a preview
> - [ ] Attach a picture of extension while creating a PR 
> 
> Create a PR 🥳
> Happy contributing 🎊 

I think I can do this. Please assign me this project.

**Comment by ritika-saha** [comment]
I want to work on this issue under JWOC. Please assign this to me 😊

**Comment by harshita214** [comment]
Hey, @ritika-saha assigning this issue to you. All the best 👍 

@Sneha0324 please look for another issue

**Comment by harshita214** [comment]
Completed - #22
