### ISSUE TITLE
feat : Compound Interest calculator

### ISSUE THREAD

**Issue by harshita214** [harshita214/Chrome-Extension#43]
Add a compound interest calculator that will take input and generate compound interest by calculating it.

- [ ] Input field for Principal amount, Rate, Time (in years), Total amount
- [ ] Output field 
- [ ] Button for Calculate
- [ ] Button for Clear
- [ ] A good UI
- [ ] All codes in one folder

Happy contributions 🎊

**Comment by 03amir** [comment]
i want to work on this issue under jwoc

**Comment by harshita214** [comment]
Sure @03amir assigning you, All the best 👍

**Comment by r3yc0n1c** [comment]
I want to work on this issue under JWOC

**Comment by harshita214** [comment]
Completed - #54
