### ISSUE TITLE
feat : extension for spacing between letters

### ISSUE THREAD

**Issue by harshita214** [harshita214/Chrome-Extension#5]
For disabled people facing problems while reading due to space between letters, build an extension that can do text spacing.

- [ ] Add at three spacing options like light spacing where spacing is 2px, moderate has 4px and extra-large has 6px
- [ ] Create a folder and add all the code
- [ ] Create a readme file for preview 
- [ ] Attach a picture of extension while creating a PR 

Happy contributing 🎊

**Comment by manya0210** [comment]
Hey!! I want to work on this issue under JWOC.

**Comment by harshita214** [comment]
Hey @manya0210, great! Assigning the issue to you. All the best 👍

**Comment by manya0210** [comment]
Thanks ...will do my best :)

**Comment by whiteHatpro** [comment]
Hey!! I want to work on this issue under JWOC.

**Comment by 03amir** [comment]
I want to work on this issue under JWOC

**Comment by harshita214** [comment]
@manya0210 due to your unavailability unassigning you

**Comment by harshita214** [comment]
@03amir assigning you. All the best 👍 
You have 3 days to complete this

@whiteHatpro since you are already working on creating an extension

**Comment by whiteHatpro** [comment]
@harshita214  no issues!!

**Comment by harshita214** [comment]
Completed - #46
