### ISSUE TITLE
feat : Hex code color picker extension

### ISSUE THREAD

**Issue by harshita214** [harshita214/Chrome-Extension#51]
Make a color code picker extension which will give hex code of color when picker/arrow/pointer will point

**Comment by whiteHatpro** [comment]
I want to work on this issue under JWoC

**Comment by harshita214** [comment]
Sure @whiteHatpro ,All the best 👍

**Comment by ayush-sleeping** [comment]
> I want to work on this issue under JWoC

Hey Mohak , If you need any help in making this extension, Let me know on discord , <br>
<br>

( Actually , I forget to comment on this issue , That I want to work on this issue 2 days ago , And I have started to making it and the extension is ready today , Yaa I know its my mistake , But if you want any help , you can contact me on discord .  )

**Comment by whiteHatpro** [comment]
> > I want to work on this issue under JWoC
> 
> Hey Mohak , If you need any help in making this extension, Let me know on discord ,
> 
> ( Actually , I forget to comment on this issue 2 days ago , That I want to work on this issue , And I have started to making it and the extension is ready today , Yaa I know its my mistake , But if you want any help , you can contact me on discord . )

@ayush-sleeping sure man!!

**Comment by harshita214** [comment]
Completed - #61
