### ISSUE TITLE
feat : meaning of word extension

### ISSUE THREAD

**Issue by harshita214** [harshita214/Chrome-Extension#52]
Make a simple extension that will give the meaning of the word when clicked on search.

**Comment by harshita214** [comment]
Sure @Devmindtk , All the best 👍

**Comment by wasimreja** [comment]
@harshita214 I would like to work on this issue under JWoC.

**Comment by harshita214** [comment]
@Devmindtk update?

**Comment by Devmindtk** [comment]
> @Devmindtk update?
Yeah  just give me a hour .
almost completed

**Comment by harshita214** [comment]
Sure make a PR 🚀

**Comment by wasimreja** [comment]
Is it not done yet?

**Comment by Devmindtk** [comment]
> Sure make a PR 🚀

check is it fine after that i will create PR
![Screenshot (500)](https://user-images.githubusercontent.com/91221069/154041425-a1e9da89-753b-4681-ab39-882d155dc836.png)
