### ISSUE TITLE
feat: wordle solver extension

### ISSUE THREAD

**Issue by ronitblenz** [harshita214/Chrome-Extension#57]
Hey, please assign me to this issue

**Comment by harshita214** [comment]
Sure but firstly kindly explain the extension in brief, its working and its features also

**Comment by ronitblenz** [comment]
@harshita214 It is not an Easy issue, plz upgrade it to Hard, it will take time to build this

**Comment by harshita214** [comment]
I see, I can assign you medium level

**Comment by ronitblenz** [comment]
Plz check and merge my PR

**Comment by harshita214** [comment]
@ronitblenz ??

**Comment by ronitblenz** [comment]
I am actually out of station for now,  You can check if its working. I am replying from my phone. Its completely on you, if you want to take it or reject it. I am sorry that I couldnt help

**Comment by harshita214** [comment]
I see, so for how period are you not available?

**Comment by harshita214** [comment]
@ronitblenz ?

**Comment by ronitblenz** [comment]
Merge it if you feel like ...
No compulsion

**Comment by whiteHatpro** [comment]
@harshita214 I want to work on this issue under JWoC

**Comment by whiteHatpro** [comment]
> @harshita214 I want to work on this issue under JWoC

@harshita214 please assign this to me

**Comment by harshita214** [comment]
Completed - #137
