### ISSUE TITLE
feat: tumbler tags

### ISSUE THREAD

**Issue by whiteHatpro** [harshita214/Chrome-Extension#59]
View all tags on a Tumblr post without clicking “see all”

**Comment by whiteHatpro** [comment]
@harshita214 please assign this issue to me

**Comment by harshita214** [comment]
Sure , can you explain this issue more briefly with its working

**Comment by whiteHatpro** [comment]
This is a Chrome Extension that lets you browse your Tumblr - Dashboard in a style similar to Pinterest which means you have multiple columns of posts that are nicely aligned, so more information fits on your screen. You can customize the look of your dashboard through the settings of the extension

**Comment by harshita214** [comment]
You can take 2 days, its alright 👍
