### ISSUE TITLE
feat : create a extension to highlight links

### ISSUE THREAD

**Issue by harshita214** [harshita214/Chrome-Extension#6]
Sometimes when we are visiting websites, we wish to view all links. So make an extension that will highlight all links present on the webpage.

- [ ] Create a folder and add all code
- [ ] Create a readme file for preview
- [ ] Attach a picture of extension while creating a PR for preview

Create a PR 🥳 
Happy contributing 🎊

**Comment by Devmindtk** [comment]
I would like to work on this issue @harshita214  please assign it to me.

**Comment by Devmindtk** [comment]
> Sometimes when we are visiting websites, we wish to view all links. So make an extension that will highlight all links present on the webpage.
> 
> * [ ]  Create a folder and add all code
> * [ ]  Create a readme file for preview
> * [ ]  Attach a picture of extension while creating a PR for preview
> 
> Create a PR 🥳 Happy contributing 🎊

I would like to work on this issue @harshita214 please assign it to me.

**Comment by thatsuman** [comment]
Hi,
I would like to work on this issue under JWOC

**Comment by raxvab** [comment]
I want to work on this issue under JWOC

**Comment by harshita214** [comment]
Hi @thatsuman you can work on this issue, assigning it to you. All the best 👍 

@raxvab @Devmindtk please work on other issues

**Comment by raxvab** [comment]
Thanks @harshita214

**Comment by whiteHatpro** [comment]
I want to work on this issue under JWOC
