### ISSUE TITLE
Feat: Weather app extension 

### ISSUE THREAD

**Issue by Srijita-Mandal** [harshita214/Chrome-Extension#60]
I want to work on this under JWOC

**Comment by harshita214** [comment]
Can you explain more, what it will be its features, how will you be showing this, are u using any API to display current weather forecast, can different locations weather can be viewed from this extension

**Comment by Srijita-Mandal** [comment]
Yah.. It takes the current location of the user and displays the weather of that area in a popup. I'll use Open weather map API for this.

**Comment by harshita214** [comment]
Sure go ahead assigning you 
All the best

**Comment by harshita214** [comment]
Completed - #69
