### ISSUE TITLE
feat : Memory Game Extension .

### ISSUE THREAD

**Issue by ayush-sleeping** [harshita214/Chrome-Extension#66]
In this Game , 
You are given a set of cards containing images which are turned to the back, 
when you click on an image, it flips over and reveals the image.
If you click on two images that are exactly the same, that is a win for you .

<br>

#

Hey @harshita214 , I want to work on this issue under JWOC'22 . 
Thanks .

**Comment by harshita214** [comment]
I see, can you tell what will be the no of grids available in this extension. Also what will happen if two similar cards will come, will after that new grid will be shown?

**Comment by ayush-sleeping** [comment]
There will be 4 x 4 no. of grids and when you will get 2 similar cards it will stay open ,
and you have try to guess others also , if you get all cards then game is over and it will your points ,
And score depends on , how much chance you will take to complete the game .

**Comment by harshita214** [comment]
Okay sure, you can go ahead and start building this extension 
All the best 👍
