### ISSUE TITLE
feat : Timer Extension

### ISSUE THREAD

**Issue by harshita214** [harshita214/Chrome-Extension#7]
In competitive coding time plays a major role so why not make a timer for all those coders out there to increase their efficiency. Make a new extension called Timer. Add an input field for a time(minutes) along with two buttons of START, STOP. Also, a reset icon for changing time is entered in the input field.

- [ ] Add input field
- [ ] Add a reset button
- [ ] Add two buttons START, STOP
- [ ] Add all the code in a folder 

Create a PR 
Happy contributing 🎊

**Comment by Shreyan-12345** [comment]
If i work,then can i rewrite the whole alarm clock code in background.js?

**Comment by varunwho** [comment]
@harshita214 Can I work on this issue under JWOC?

**Comment by harshita214** [comment]
Hy @Shreyan-12345 @varunwho, for this issue I am converting it to a new extension of the Timer Alarm Clock. So you have to build the timer extension which will have an input field for a time(minutes) along with two buttons of START, STOP. Along with a reset icon for changing time is entered in the input field. I am changing this to a new extension as the Alarm clock is already made. I am giving both of you first priority for that issue as you commented on this.

**Comment by DarkFalc0n** [comment]
I want to work on this issue under JWOC

**Comment by harshita214** [comment]
Sure @DarkFalc0n, Go ahead assigning it to you. All the best 👍
When you create PR make sure to add a screenshot for a preview

**Comment by harshita214** [comment]
Completed - #31
