### ISSUE TITLE
feat: password generator

### ISSUE THREAD

**Issue by r3yc0n1c** [harshita214/Chrome-Extension#71]
This extension will generate a strong random password of variable length (given by the user)

Hi @harshita214, I would like to contribute to this issue under JWOC'22.
Thanks.

**Comment by harshita214** [comment]
Will it save also the password?

**Comment by r3yc0n1c** [comment]
> Will it save also the password?

for now, it'll just create random passwords of variable length but I can update that to store the password  later

**Comment by r3yc0n1c** [comment]
yes

**Comment by harshita214** [comment]
Okay are u able to complete this in 1-2 days?

**Comment by r3yc0n1c** [comment]
I need 2-3 days to code and add a good UI

**Comment by harshita214** [comment]
Can you brief the issue and its features
Like user can add a number then the password will be generated?
Is there any other features etc.

**Comment by harshita214** [comment]
Okay

**Comment by harshita214** [comment]
@r3yc0n1c update?

**Comment by r3yc0n1c** [comment]
> @r3yc0n1c update?

yep... just removed the commented lines and was working on the UI... can you review the PR now?

**Comment by harshita214** [comment]
Completed - #93
