### ISSUE TITLE
feat : rgb to hex / hex to rgb converter

### ISSUE THREAD

**Issue by mnnkhndlwl** [harshita214/Chrome-Extension#74]
in this extension user can simply input any rgb value or hex value or at moment user input that value this extension will automatically 
convert to corresponding hex / rgb value user don't need to press any button to convert values

**Comment by harshita214** [comment]
Okay are u adding all the options as shown below 

![image](https://user-images.githubusercontent.com/79797000/154262235-5e3398d3-51df-4adc-a755-d73a87b1d522.png)

You can also consider as an example

**Comment by mnnkhndlwl** [comment]
it's not going to have reset or swap button

**Comment by harshita214** [comment]
Then how will user convert it or reset the values?

**Comment by mnnkhndlwl** [comment]
As soon as user enter a valid input it will automatically generate the corresponding value 
and if user wants to enter any other value user can simply use backspace key
it's simple

**Comment by harshita214** [comment]
Okay but what about the converter how will the user do that since there is no swap button

**Comment by mnnkhndlwl** [comment]
just assign me this issue when this  extension will be completed you will see that there is no need of swap button

**Comment by harshita214** [comment]
Okay
