### ISSUE TITLE
feat : font and text size changer 

### ISSUE THREAD

**Issue by harshita214** [harshita214/Chrome-Extension#76]
Make an extension that can change the font style. Add different font styles which can be changed. Also, add an option for increasing and decreasing text size.

- [ ] Different Fonts can be enabled
- [ ] Increase text size option
- [ ] Decrease text size option
- [ ] All codes in one folder
- [ ] Add readme file with preview picture and video of extension implementation

All the best 👍

**Comment by whiteHatpro** [comment]
I want to work on this issue under JWoC

**Comment by harshita214** [comment]
Sure @whiteHatpro All the best 👍

**Comment by harshita214** [comment]
Completed - #80
