### ISSUE TITLE
feat: customized site blocker

### ISSUE THREAD

**Issue by whiteHatpro** [harshita214/Chrome-Extension#79]
If you’ve blocked an app or a website you can unlock it with a passcode of your choosing, making it that bit harder to procrastinate. You can also password protect the options page to keep you from easily removing sites from your list.
timer to schedule the site blocking and much more

**Comment by whiteHatpro** [comment]
I want to work on this issue under JWoC

**Comment by harshita214** [comment]
Okay, Sure assigning you 🚀 
All the best 👍

**Comment by harshita214** [comment]
Completed - #83
