### ISSUE TITLE
fix : UI improvement for Tab Tracker

### ISSUE THREAD

**Issue by harshita214** [harshita214/Chrome-Extension#8]
This is the current UI, from your creativity improve its colors or design or anything it's totally up to you!
Ps: You can change its icon also

![image](https://user-images.githubusercontent.com/79797000/151491383-60ef4e38-8b50-4e7c-996e-591d2cc25bad.png)

While creating a PR, add a preview picture to view the changes.
Happy contributing 🎊

**Comment by varunwho** [comment]
@harshita214 Can I work on this?

**Comment by Lavanyabisht11** [comment]
I want to work on this issue under JWOC

**Comment by Lavanyabisht11** [comment]
I want to work on this issue under JWOC

**Comment by harshita214** [comment]
hey, @Lavanyabisht11 assigning issue to you. All the best 👍 

@varunwho Please look for another issue

**Comment by DarkFalc0n** [comment]
I want to work on this issue under JWOC

**Comment by harshita214** [comment]
Okay, @DarkFalc0n assigning you. All the best 👍

**Comment by harshita214** [comment]
Completed - #35
