### ISSUE TITLE
feat : BMI Calculator .

### ISSUE THREAD

**Issue by ayush-sleeping** [harshita214/Chrome-Extension#81]
So , what is BMI Calculator : 

Body mass index (BMI) is a measure of body fat based on height and weight that applies to adult men and women.
Body Mass Index calculator gives out the BMI value and categorizes BMI based on provided information .

here what I will make ,
In the first box it will ask your weight and in the second box it will ask your height , and then you have press the button ( calculate ),
and it will show (result) you your BMI (Body mass index)  , 

# 

hey @harshita214 , I want to work on this issue under JWOC'22 .

**Comment by harshita214** [comment]
Sure @ayush-sleeping

**Comment by harshita214** [comment]
Update @ayush-sleeping

**Comment by ayush-sleeping** [comment]
> Update @ayush-sleeping 

Yaaa , It's completed .... Going to add now

**Comment by harshita214** [comment]
Completed - #89
