### ISSUE TITLE
feat: Dark Mode palette generator

### ISSUE THREAD

**Issue by DarkFalc0n** [harshita214/Chrome-Extension#82]
Dark mode is now a very trendy design style owing to the growth of AMOLED display and how good dark UI look in them. However, designers lack a handy color palette generator that can generate dark mode on the fly. The dark mode palette generator will address this issue by generating custom dark color palettes for UI designers.
It will feature a slider like this:
![image](https://user-images.githubusercontent.com/59203815/154795848-2853c79f-ecd4-4227-92b1-9460dd595676.png)
It will enable the user to pick a specific hue and then create beautiful palettes based off that color. It will also feature a copy-on-click feature for hex codes.

See [this](https://www.instagram.com/p/CWdRERNPzWV/) for reference on the generation method.

**Comment by harshita214** [comment]
Okay so from the slider user will choose a single color and based on that a palette of colors will be displayed , How many colors will be displayed?

**Comment by DarkFalc0n** [comment]
> Okay so from the slider user will choose a single color and based on that a palette of colors will be displayed , How many colors will be displayed?

As per International standards of business and formal Web/App design conventions, these are the basic colors in any Color palette: 

```
Primary Text
Secondary Text
Tertiary Text
Accent
Card 
Background
Call-to-action (CTA)
```
All these will be available in the extension

**Comment by harshita214** [comment]
Sure @DarkFalc0n assigning you
All the best 👍

**Comment by harshita214** [comment]
Completed - #97
