### ISSUE TITLE
feat: Snippet Highlighter

### ISSUE THREAD

**Issue by whiteHatpro** [harshita214/Chrome-Extension#85]
Highlighter tool to annotate websites and PDF, import Kindle highlights, and more.
Get all your highlights in one place, instantly searchable, available wherever you go

**Comment by whiteHatpro** [comment]
@harshita214 i want to work on this issue under JWoC

**Comment by harshita214** [comment]
Sure, assigning you 
All the best 👍

**Comment by harshita214** [comment]
Completed - #94
