### ISSUE TITLE
feat : random gradient generator

### ISSUE THREAD

**Issue by mnnkhndlwl** [harshita214/Chrome-Extension#87]

**Comment by mnnkhndlwl** [comment]
i want to work on this issue under jwoc

**Comment by mnnkhndlwl** [comment]
this extension is gonna have a generate button which will generate any random gradient on click for user
and user can copy that and use it in projects
it will show the preview of generated gradient

**Comment by harshita214** [comment]
So you will be giving the option for angle, adding no of colors?

**Comment by mnnkhndlwl** [comment]
@harshita214  ???

**Comment by harshita214** [comment]
I see okay okay , so there are two options only then right?

**Comment by harshita214** [comment]
Completed - #102
