### ISSUE TITLE
feat : Contrast Colors extension

### ISSUE THREAD

**Issue by harshita214** [harshita214/Chrome-Extension#91]
In this extension, the user will have 4 options for changing contrast

- [ ] 1.  Invert colors
- [ ] 2.  Dark contrast
- [ ] 3.  Desaturate
- [ ] 4.  Light contrast
- [ ] All codes in one folder
- [ ] A nice UI

All the best 🎊

**Comment by whiteHatpro** [comment]
@harshita214 do you want these setting to be applied to whole page or some part as selected?

**Comment by harshita214** [comment]
Whole web page

**Comment by whiteHatpro** [comment]
okay

**Comment by harshita214** [comment]
Sure @whiteHatpro 
Assigning you 
All the best 👍

**Comment by harshita214** [comment]
Completed - #108
