### ISSUE TITLE
feat :  Quadratic Equation

### ISSUE THREAD

**Issue by harshita214** [harshita214/Chrome-Extension#92]
User will enter coefficients of a,b and c. After that discriminant and roots will be displayed.

- [ ] Take input a,b,c
- [ ] Give output as discriminant and roots
- [ ] All codes in one folder
- [ ] A nice UI

All the best 🎊

**Comment by saujanyaraj07** [comment]
@harshita214 Pl assign me this issue under JWOC'22.

**Comment by harshita214** [comment]
Sure @saujanyaraj07 
Assigned ,All the best 👍

**Comment by harshita214** [comment]
Completed - #96
