### ISSUE TITLE
feat: timezone converter extension

### ISSUE THREAD

**Issue by r3yc0n1c** [harshita214/Chrome-Extension#98]
A google chrome extension to compare and convert time to all the major time zones across the world.

Features:
- [ ] converts time instantly
- [ ] supports major time zones

will add more features in the future...

**Comment by r3yc0n1c** [comment]
Hey @harshita214, I want to work on this issue under JWoC'22

**Comment by r3yc0n1c** [comment]
yes, it will convert the current time to any timezone and they can enter the time manually also to convert it from a specific timezone to other

**Comment by harshita214** [comment]
Sure assigning you 
All the best 👍

**Comment by harshita214** [comment]
Update ??

**Comment by r3yc0n1c** [comment]
working on it... 
- [x] done with fetching the data 
- [ ] working on UI

**Comment by harshita214** [comment]
Completed - #110
